// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConnectionsColumns holds the columns for the "connections" table.
	ConnectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "config", Type: field.TypeString, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "secret_ciphertext", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "unknown"},
		{Name: "status_message", Type: field.TypeString, Default: ""},
		{Name: "status_checked_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ConnectionsTable holds the schema information for the "connections" table.
	ConnectionsTable = &schema.Table{
		Name:       "connections",
		Columns:    ConnectionsColumns,
		PrimaryKey: []*schema.Column{ConnectionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "connection_user_id_provider_created_at",
				Unique:  false,
				Columns: []*schema.Column{ConnectionsColumns[1], ConnectionsColumns[2], ConnectionsColumns[9]},
			},
		},
	}
	// NocodbBackupPoliciesColumns holds the columns for the "nocodb_backup_policies" table.
	NocodbBackupPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "connection_id", Type: field.TypeString},
		{Name: "base_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool},
		{Name: "cron", Type: field.TypeString},
		{Name: "retention", Type: field.TypeInt},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NocodbBackupPoliciesTable holds the schema information for the "nocodb_backup_policies" table.
	NocodbBackupPoliciesTable = &schema.Table{
		Name:       "nocodb_backup_policies",
		Columns:    NocodbBackupPoliciesColumns,
		PrimaryKey: []*schema.Column{NocodbBackupPoliciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "nocodbbackuppolicy_connection_id_base_id",
				Unique:  true,
				Columns: []*schema.Column{NocodbBackupPoliciesColumns[1], NocodbBackupPoliciesColumns[2]},
			},
			{
				Name:    "nocodbbackuppolicy_user_id_connection_id",
				Unique:  false,
				Columns: []*schema.Column{NocodbBackupPoliciesColumns[3], NocodbBackupPoliciesColumns[1]},
			},
		},
	}
	// NocodbSnapshotsColumns holds the columns for the "nocodb_snapshots" table.
	NocodbSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "connection_id", Type: field.TypeString},
		{Name: "base_id", Type: field.TypeString},
		{Name: "base_title", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString},
		{Name: "trigger", Type: field.TypeString},
		{Name: "error", Type: field.TypeString, Default: ""},
		{Name: "progress", Type: field.TypeString, Default: ""},
		{Name: "object_key", Type: field.TypeString, Default: ""},
		{Name: "size_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "record_count", Type: field.TypeInt64, Default: 0},
		{Name: "link_count", Type: field.TypeInt64, Default: 0},
		{Name: "tables", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// NocodbSnapshotsTable holds the schema information for the "nocodb_snapshots" table.
	NocodbSnapshotsTable = &schema.Table{
		Name:       "nocodb_snapshots",
		Columns:    NocodbSnapshotsColumns,
		PrimaryKey: []*schema.Column{NocodbSnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "nocodbsnapshot_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{NocodbSnapshotsColumns[1], NocodbSnapshotsColumns[14]},
			},
			{
				Name:    "nocodbsnapshot_connection_id_base_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{NocodbSnapshotsColumns[2], NocodbSnapshotsColumns[3], NocodbSnapshotsColumns[14]},
			},
			{
				Name:    "nocodbsnapshot_status",
				Unique:  false,
				Columns: []*schema.Column{NocodbSnapshotsColumns[5]},
			},
		},
	}
	// OauthStatesColumns holds the columns for the "oauth_states" table.
	OauthStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "redirect_uri", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// OauthStatesTable holds the schema information for the "oauth_states" table.
	OauthStatesTable = &schema.Table{
		Name:       "oauth_states",
		Columns:    OauthStatesColumns,
		PrimaryKey: []*schema.Column{OauthStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthstate_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthStatesColumns[4]},
			},
		},
	}
	// AuthSessionsColumns holds the columns for the "auth_sessions" table.
	AuthSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked", Type: field.TypeBool, Default: false},
	}
	// AuthSessionsTable holds the schema information for the "auth_sessions" table.
	AuthSessionsTable = &schema.Table{
		Name:       "auth_sessions",
		Columns:    AuthSessionsColumns,
		PrimaryKey: []*schema.Column{AuthSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AuthSessionsColumns[4]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString, Default: ""},
		{Name: "avatar_url", Type: field.TypeString, Default: ""},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "external_id", Type: field.TypeString, Default: ""},
		{Name: "password_hash", Type: field.TypeString, Default: ""},
		{Name: "role", Type: field.TypeString, Default: ""},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_provider_external_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[5], UsersColumns[6]},
				Annotation: &entsql.IndexAnnotation{
					Where: "external_id <> ''",
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConnectionsTable,
		NocodbBackupPoliciesTable,
		NocodbSnapshotsTable,
		OauthStatesTable,
		AuthSessionsTable,
		UsersTable,
	}
)

func init() {
	ConnectionsTable.Annotation = &entsql.Annotation{
		Table: "connections",
	}
	NocodbBackupPoliciesTable.Annotation = &entsql.Annotation{
		Table: "nocodb_backup_policies",
	}
	NocodbSnapshotsTable.Annotation = &entsql.Annotation{
		Table: "nocodb_snapshots",
	}
	OauthStatesTable.Annotation = &entsql.Annotation{
		Table: "oauth_states",
	}
	AuthSessionsTable.Annotation = &entsql.Annotation{
		Table: "auth_sessions",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
