// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/alert"
	"go.orx.me/apps/neo-box/internal/ent/predicate"
)

// AlertUpdate is the builder for updating Alert entities.
type AlertUpdate struct {
	config
	hooks    []Hook
	mutation *AlertMutation
}

// Where appends a list predicates to the AlertUpdate builder.
func (_u *AlertUpdate) Where(ps ...predicate.Alert) *AlertUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *AlertUpdate) SetDeliveredAt(v time.Time) *AlertUpdate {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableDeliveredAt(v *time.Time) *AlertUpdate {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *AlertUpdate) ClearDeliveredAt() *AlertUpdate {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetDeliveryError sets the "delivery_error" field.
func (_u *AlertUpdate) SetDeliveryError(v string) *AlertUpdate {
	_u.mutation.SetDeliveryError(v)
	return _u
}

// SetNillableDeliveryError sets the "delivery_error" field if the given value is not nil.
func (_u *AlertUpdate) SetNillableDeliveryError(v *string) *AlertUpdate {
	if v != nil {
		_u.SetDeliveryError(*v)
	}
	return _u
}

// Mutation returns the AlertMutation object of the builder.
func (_u *AlertUpdate) Mutation() *AlertMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlertUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlertUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AlertUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(alert.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(alert.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeliveryError(); ok {
		_spec.SetField(alert.FieldDeliveryError, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlertUpdateOne is the builder for updating a single Alert entity.
type AlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertMutation
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *AlertUpdateOne) SetDeliveredAt(v time.Time) *AlertUpdateOne {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableDeliveredAt(v *time.Time) *AlertUpdateOne {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *AlertUpdateOne) ClearDeliveredAt() *AlertUpdateOne {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetDeliveryError sets the "delivery_error" field.
func (_u *AlertUpdateOne) SetDeliveryError(v string) *AlertUpdateOne {
	_u.mutation.SetDeliveryError(v)
	return _u
}

// SetNillableDeliveryError sets the "delivery_error" field if the given value is not nil.
func (_u *AlertUpdateOne) SetNillableDeliveryError(v *string) *AlertUpdateOne {
	if v != nil {
		_u.SetDeliveryError(*v)
	}
	return _u
}

// Mutation returns the AlertMutation object of the builder.
func (_u *AlertUpdateOne) Mutation() *AlertMutation {
	return _u.mutation
}

// Where appends a list predicates to the AlertUpdate builder.
func (_u *AlertUpdateOne) Where(ps ...predicate.Alert) *AlertUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlertUpdateOne) Select(field string, fields ...string) *AlertUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Alert entity.
func (_u *AlertUpdateOne) Save(ctx context.Context) (*Alert, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertUpdateOne) SaveX(ctx context.Context) *Alert {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlertUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AlertUpdateOne) sqlSave(ctx context.Context) (_node *Alert, err error) {
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Alert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alert.FieldID)
		for _, f := range fields {
			if !alert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(alert.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(alert.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeliveryError(); ok {
		_spec.SetField(alert.FieldDeliveryError, field.TypeString, value)
	}
	_node = &Alert{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
