// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/cloudflarednsoperation"
	"go.orx.me/apps/neo-box/internal/ent/predicate"
)

// CloudflareDNSOperationDelete is the builder for deleting a CloudflareDNSOperation entity.
type CloudflareDNSOperationDelete struct {
	config
	hooks    []Hook
	mutation *CloudflareDNSOperationMutation
}

// Where appends a list predicates to the CloudflareDNSOperationDelete builder.
func (_d *CloudflareDNSOperationDelete) Where(ps ...predicate.CloudflareDNSOperation) *CloudflareDNSOperationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CloudflareDNSOperationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CloudflareDNSOperationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CloudflareDNSOperationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cloudflarednsoperation.Table, sqlgraph.NewFieldSpec(cloudflarednsoperation.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CloudflareDNSOperationDeleteOne is the builder for deleting a single CloudflareDNSOperation entity.
type CloudflareDNSOperationDeleteOne struct {
	_d *CloudflareDNSOperationDelete
}

// Where appends a list predicates to the CloudflareDNSOperationDelete builder.
func (_d *CloudflareDNSOperationDeleteOne) Where(ps ...predicate.CloudflareDNSOperation) *CloudflareDNSOperationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CloudflareDNSOperationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cloudflarednsoperation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CloudflareDNSOperationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
