// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/connection"
)

// ConnectionCreate is the builder for creating a Connection entity.
type ConnectionCreate struct {
	config
	mutation *ConnectionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *ConnectionCreate) SetUserID(v string) *ConnectionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ConnectionCreate) SetProvider(v string) *ConnectionCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ConnectionCreate) SetName(v string) *ConnectionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *ConnectionCreate) SetConfig(v jsontext.Value) *ConnectionCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetSecretCiphertext sets the "secret_ciphertext" field.
func (_c *ConnectionCreate) SetSecretCiphertext(v string) *ConnectionCreate {
	_c.mutation.SetSecretCiphertext(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ConnectionCreate) SetStatus(v string) *ConnectionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ConnectionCreate) SetNillableStatus(v *string) *ConnectionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStatusMessage sets the "status_message" field.
func (_c *ConnectionCreate) SetStatusMessage(v string) *ConnectionCreate {
	_c.mutation.SetStatusMessage(v)
	return _c
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_c *ConnectionCreate) SetNillableStatusMessage(v *string) *ConnectionCreate {
	if v != nil {
		_c.SetStatusMessage(*v)
	}
	return _c
}

// SetStatusCheckedAt sets the "status_checked_at" field.
func (_c *ConnectionCreate) SetStatusCheckedAt(v time.Time) *ConnectionCreate {
	_c.mutation.SetStatusCheckedAt(v)
	return _c
}

// SetNillableStatusCheckedAt sets the "status_checked_at" field if the given value is not nil.
func (_c *ConnectionCreate) SetNillableStatusCheckedAt(v *time.Time) *ConnectionCreate {
	if v != nil {
		_c.SetStatusCheckedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConnectionCreate) SetCreatedAt(v time.Time) *ConnectionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConnectionCreate) SetUpdatedAt(v time.Time) *ConnectionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ConnectionCreate) SetID(v string) *ConnectionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ConnectionMutation object of the builder.
func (_c *ConnectionCreate) Mutation() *ConnectionMutation {
	return _c.mutation
}

// Save creates the Connection in the database.
func (_c *ConnectionCreate) Save(ctx context.Context) (*Connection, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConnectionCreate) SaveX(ctx context.Context) *Connection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConnectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConnectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConnectionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := connection.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StatusMessage(); !ok {
		v := connection.DefaultStatusMessage
		_c.mutation.SetStatusMessage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConnectionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Connection.user_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "Connection.provider"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Connection.name"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "Connection.config"`)}
	}
	if _, ok := _c.mutation.SecretCiphertext(); !ok {
		return &ValidationError{Name: "secret_ciphertext", err: errors.New(`ent: missing required field "Connection.secret_ciphertext"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Connection.status"`)}
	}
	if _, ok := _c.mutation.StatusMessage(); !ok {
		return &ValidationError{Name: "status_message", err: errors.New(`ent: missing required field "Connection.status_message"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Connection.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Connection.updated_at"`)}
	}
	return nil
}

func (_c *ConnectionCreate) sqlSave(ctx context.Context) (*Connection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Connection.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConnectionCreate) createSpec() (*Connection, *sqlgraph.CreateSpec) {
	var (
		_node = &Connection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(connection.Table, sqlgraph.NewFieldSpec(connection.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(connection.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(connection.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(connection.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(connection.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.SecretCiphertext(); ok {
		_spec.SetField(connection.FieldSecretCiphertext, field.TypeString, value)
		_node.SecretCiphertext = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(connection.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StatusMessage(); ok {
		_spec.SetField(connection.FieldStatusMessage, field.TypeString, value)
		_node.StatusMessage = value
	}
	if value, ok := _c.mutation.StatusCheckedAt(); ok {
		_spec.SetField(connection.FieldStatusCheckedAt, field.TypeTime, value)
		_node.StatusCheckedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(connection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(connection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Connection.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConnectionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ConnectionCreate) OnConflict(opts ...sql.ConflictOption) *ConnectionUpsertOne {
	_c.conflict = opts
	return &ConnectionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Connection.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConnectionCreate) OnConflictColumns(columns ...string) *ConnectionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConnectionUpsertOne{
		create: _c,
	}
}

type (
	// ConnectionUpsertOne is the builder for "upsert"-ing
	//  one Connection node.
	ConnectionUpsertOne struct {
		create *ConnectionCreate
	}

	// ConnectionUpsert is the "OnConflict" setter.
	ConnectionUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ConnectionUpsert) SetName(v string) *ConnectionUpsert {
	u.Set(connection.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ConnectionUpsert) UpdateName() *ConnectionUpsert {
	u.SetExcluded(connection.FieldName)
	return u
}

// SetConfig sets the "config" field.
func (u *ConnectionUpsert) SetConfig(v jsontext.Value) *ConnectionUpsert {
	u.Set(connection.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ConnectionUpsert) UpdateConfig() *ConnectionUpsert {
	u.SetExcluded(connection.FieldConfig)
	return u
}

// SetSecretCiphertext sets the "secret_ciphertext" field.
func (u *ConnectionUpsert) SetSecretCiphertext(v string) *ConnectionUpsert {
	u.Set(connection.FieldSecretCiphertext, v)
	return u
}

// UpdateSecretCiphertext sets the "secret_ciphertext" field to the value that was provided on create.
func (u *ConnectionUpsert) UpdateSecretCiphertext() *ConnectionUpsert {
	u.SetExcluded(connection.FieldSecretCiphertext)
	return u
}

// SetStatus sets the "status" field.
func (u *ConnectionUpsert) SetStatus(v string) *ConnectionUpsert {
	u.Set(connection.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConnectionUpsert) UpdateStatus() *ConnectionUpsert {
	u.SetExcluded(connection.FieldStatus)
	return u
}

// SetStatusMessage sets the "status_message" field.
func (u *ConnectionUpsert) SetStatusMessage(v string) *ConnectionUpsert {
	u.Set(connection.FieldStatusMessage, v)
	return u
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *ConnectionUpsert) UpdateStatusMessage() *ConnectionUpsert {
	u.SetExcluded(connection.FieldStatusMessage)
	return u
}

// SetStatusCheckedAt sets the "status_checked_at" field.
func (u *ConnectionUpsert) SetStatusCheckedAt(v time.Time) *ConnectionUpsert {
	u.Set(connection.FieldStatusCheckedAt, v)
	return u
}

// UpdateStatusCheckedAt sets the "status_checked_at" field to the value that was provided on create.
func (u *ConnectionUpsert) UpdateStatusCheckedAt() *ConnectionUpsert {
	u.SetExcluded(connection.FieldStatusCheckedAt)
	return u
}

// ClearStatusCheckedAt clears the value of the "status_checked_at" field.
func (u *ConnectionUpsert) ClearStatusCheckedAt() *ConnectionUpsert {
	u.SetNull(connection.FieldStatusCheckedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConnectionUpsert) SetUpdatedAt(v time.Time) *ConnectionUpsert {
	u.Set(connection.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConnectionUpsert) UpdateUpdatedAt() *ConnectionUpsert {
	u.SetExcluded(connection.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Connection.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(connection.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ConnectionUpsertOne) UpdateNewValues() *ConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(connection.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(connection.FieldUserID)
		}
		if _, exists := u.create.mutation.Provider(); exists {
			s.SetIgnore(connection.FieldProvider)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(connection.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Connection.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConnectionUpsertOne) Ignore() *ConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConnectionUpsertOne) DoNothing() *ConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConnectionCreate.OnConflict
// documentation for more info.
func (u *ConnectionUpsertOne) Update(set func(*ConnectionUpsert)) *ConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConnectionUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ConnectionUpsertOne) SetName(v string) *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ConnectionUpsertOne) UpdateName() *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateName()
	})
}

// SetConfig sets the "config" field.
func (u *ConnectionUpsertOne) SetConfig(v jsontext.Value) *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ConnectionUpsertOne) UpdateConfig() *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateConfig()
	})
}

// SetSecretCiphertext sets the "secret_ciphertext" field.
func (u *ConnectionUpsertOne) SetSecretCiphertext(v string) *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetSecretCiphertext(v)
	})
}

// UpdateSecretCiphertext sets the "secret_ciphertext" field to the value that was provided on create.
func (u *ConnectionUpsertOne) UpdateSecretCiphertext() *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateSecretCiphertext()
	})
}

// SetStatus sets the "status" field.
func (u *ConnectionUpsertOne) SetStatus(v string) *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConnectionUpsertOne) UpdateStatus() *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateStatus()
	})
}

// SetStatusMessage sets the "status_message" field.
func (u *ConnectionUpsertOne) SetStatusMessage(v string) *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetStatusMessage(v)
	})
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *ConnectionUpsertOne) UpdateStatusMessage() *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateStatusMessage()
	})
}

// SetStatusCheckedAt sets the "status_checked_at" field.
func (u *ConnectionUpsertOne) SetStatusCheckedAt(v time.Time) *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetStatusCheckedAt(v)
	})
}

// UpdateStatusCheckedAt sets the "status_checked_at" field to the value that was provided on create.
func (u *ConnectionUpsertOne) UpdateStatusCheckedAt() *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateStatusCheckedAt()
	})
}

// ClearStatusCheckedAt clears the value of the "status_checked_at" field.
func (u *ConnectionUpsertOne) ClearStatusCheckedAt() *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.ClearStatusCheckedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConnectionUpsertOne) SetUpdatedAt(v time.Time) *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConnectionUpsertOne) UpdateUpdatedAt() *ConnectionUpsertOne {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ConnectionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConnectionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConnectionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConnectionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ConnectionUpsertOne.ID is not supported by MySQL driver. Use ConnectionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConnectionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConnectionCreateBulk is the builder for creating many Connection entities in bulk.
type ConnectionCreateBulk struct {
	config
	err      error
	builders []*ConnectionCreate
	conflict []sql.ConflictOption
}

// Save creates the Connection entities in the database.
func (_c *ConnectionCreateBulk) Save(ctx context.Context) ([]*Connection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Connection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConnectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConnectionCreateBulk) SaveX(ctx context.Context) []*Connection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConnectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConnectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Connection.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConnectionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ConnectionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConnectionUpsertBulk {
	_c.conflict = opts
	return &ConnectionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Connection.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConnectionCreateBulk) OnConflictColumns(columns ...string) *ConnectionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConnectionUpsertBulk{
		create: _c,
	}
}

// ConnectionUpsertBulk is the builder for "upsert"-ing
// a bulk of Connection nodes.
type ConnectionUpsertBulk struct {
	create *ConnectionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Connection.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(connection.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ConnectionUpsertBulk) UpdateNewValues() *ConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(connection.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(connection.FieldUserID)
			}
			if _, exists := b.mutation.Provider(); exists {
				s.SetIgnore(connection.FieldProvider)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(connection.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Connection.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConnectionUpsertBulk) Ignore() *ConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConnectionUpsertBulk) DoNothing() *ConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConnectionCreateBulk.OnConflict
// documentation for more info.
func (u *ConnectionUpsertBulk) Update(set func(*ConnectionUpsert)) *ConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConnectionUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ConnectionUpsertBulk) SetName(v string) *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ConnectionUpsertBulk) UpdateName() *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateName()
	})
}

// SetConfig sets the "config" field.
func (u *ConnectionUpsertBulk) SetConfig(v jsontext.Value) *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ConnectionUpsertBulk) UpdateConfig() *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateConfig()
	})
}

// SetSecretCiphertext sets the "secret_ciphertext" field.
func (u *ConnectionUpsertBulk) SetSecretCiphertext(v string) *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetSecretCiphertext(v)
	})
}

// UpdateSecretCiphertext sets the "secret_ciphertext" field to the value that was provided on create.
func (u *ConnectionUpsertBulk) UpdateSecretCiphertext() *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateSecretCiphertext()
	})
}

// SetStatus sets the "status" field.
func (u *ConnectionUpsertBulk) SetStatus(v string) *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConnectionUpsertBulk) UpdateStatus() *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateStatus()
	})
}

// SetStatusMessage sets the "status_message" field.
func (u *ConnectionUpsertBulk) SetStatusMessage(v string) *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetStatusMessage(v)
	})
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *ConnectionUpsertBulk) UpdateStatusMessage() *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateStatusMessage()
	})
}

// SetStatusCheckedAt sets the "status_checked_at" field.
func (u *ConnectionUpsertBulk) SetStatusCheckedAt(v time.Time) *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetStatusCheckedAt(v)
	})
}

// UpdateStatusCheckedAt sets the "status_checked_at" field to the value that was provided on create.
func (u *ConnectionUpsertBulk) UpdateStatusCheckedAt() *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateStatusCheckedAt()
	})
}

// ClearStatusCheckedAt clears the value of the "status_checked_at" field.
func (u *ConnectionUpsertBulk) ClearStatusCheckedAt() *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.ClearStatusCheckedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConnectionUpsertBulk) SetUpdatedAt(v time.Time) *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConnectionUpsertBulk) UpdateUpdatedAt() *ConnectionUpsertBulk {
	return u.Update(func(s *ConnectionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ConnectionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConnectionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConnectionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConnectionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
