// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"go.orx.me/apps/neo-box/internal/ent/nocodbrestore"
	"go.orx.me/apps/neo-box/internal/repo/nocodb"
)

// NocoDBRestore is the model entity for the NocoDBRestore schema.
type NocoDBRestore struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// SnapshotID holds the value of the "snapshot_id" field.
	SnapshotID string `json:"snapshot_id,omitempty"`
	// SourceConnectionID holds the value of the "source_connection_id" field.
	SourceConnectionID string `json:"source_connection_id,omitempty"`
	// SourceBaseID holds the value of the "source_base_id" field.
	SourceBaseID string `json:"source_base_id,omitempty"`
	// SourceBaseTitle holds the value of the "source_base_title" field.
	SourceBaseTitle string `json:"source_base_title,omitempty"`
	// TargetConnectionID holds the value of the "target_connection_id" field.
	TargetConnectionID string `json:"target_connection_id,omitempty"`
	// TargetBaseID holds the value of the "target_base_id" field.
	TargetBaseID string `json:"target_base_id,omitempty"`
	// TargetBaseTitle holds the value of the "target_base_title" field.
	TargetBaseTitle string `json:"target_base_title,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress string `json:"progress,omitempty"`
	// TableCount holds the value of the "table_count" field.
	TableCount int `json:"table_count,omitempty"`
	// RecordCount holds the value of the "record_count" field.
	RecordCount int64 `json:"record_count,omitempty"`
	// LinkCount holds the value of the "link_count" field.
	LinkCount int64 `json:"link_count,omitempty"`
	// FileCount holds the value of the "file_count" field.
	FileCount int64 `json:"file_count,omitempty"`
	// ViewCount holds the value of the "view_count" field.
	ViewCount int `json:"view_count,omitempty"`
	// HookCount holds the value of the "hook_count" field.
	HookCount int `json:"hook_count,omitempty"`
	// Warnings holds the value of the "warnings" field.
	Warnings []nocodb.RestoreWarning `json:"warnings,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NocoDBRestore) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nocodbrestore.FieldWarnings:
			values[i] = new([]byte)
		case nocodbrestore.FieldTableCount, nocodbrestore.FieldRecordCount, nocodbrestore.FieldLinkCount, nocodbrestore.FieldFileCount, nocodbrestore.FieldViewCount, nocodbrestore.FieldHookCount:
			values[i] = new(sql.NullInt64)
		case nocodbrestore.FieldID, nocodbrestore.FieldUserID, nocodbrestore.FieldSnapshotID, nocodbrestore.FieldSourceConnectionID, nocodbrestore.FieldSourceBaseID, nocodbrestore.FieldSourceBaseTitle, nocodbrestore.FieldTargetConnectionID, nocodbrestore.FieldTargetBaseID, nocodbrestore.FieldTargetBaseTitle, nocodbrestore.FieldStatus, nocodbrestore.FieldError, nocodbrestore.FieldProgress:
			values[i] = new(sql.NullString)
		case nocodbrestore.FieldCreatedAt, nocodbrestore.FieldStartedAt, nocodbrestore.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NocoDBRestore fields.
func (_m *NocoDBRestore) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nocodbrestore.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case nocodbrestore.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case nocodbrestore.FieldSnapshotID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_id", values[i])
			} else if value.Valid {
				_m.SnapshotID = value.String
			}
		case nocodbrestore.FieldSourceConnectionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_connection_id", values[i])
			} else if value.Valid {
				_m.SourceConnectionID = value.String
			}
		case nocodbrestore.FieldSourceBaseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_base_id", values[i])
			} else if value.Valid {
				_m.SourceBaseID = value.String
			}
		case nocodbrestore.FieldSourceBaseTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_base_title", values[i])
			} else if value.Valid {
				_m.SourceBaseTitle = value.String
			}
		case nocodbrestore.FieldTargetConnectionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_connection_id", values[i])
			} else if value.Valid {
				_m.TargetConnectionID = value.String
			}
		case nocodbrestore.FieldTargetBaseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_base_id", values[i])
			} else if value.Valid {
				_m.TargetBaseID = value.String
			}
		case nocodbrestore.FieldTargetBaseTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_base_title", values[i])
			} else if value.Valid {
				_m.TargetBaseTitle = value.String
			}
		case nocodbrestore.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case nocodbrestore.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case nocodbrestore.FieldProgress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = value.String
			}
		case nocodbrestore.FieldTableCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field table_count", values[i])
			} else if value.Valid {
				_m.TableCount = int(value.Int64)
			}
		case nocodbrestore.FieldRecordCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field record_count", values[i])
			} else if value.Valid {
				_m.RecordCount = value.Int64
			}
		case nocodbrestore.FieldLinkCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field link_count", values[i])
			} else if value.Valid {
				_m.LinkCount = value.Int64
			}
		case nocodbrestore.FieldFileCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_count", values[i])
			} else if value.Valid {
				_m.FileCount = value.Int64
			}
		case nocodbrestore.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				_m.ViewCount = int(value.Int64)
			}
		case nocodbrestore.FieldHookCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hook_count", values[i])
			} else if value.Valid {
				_m.HookCount = int(value.Int64)
			}
		case nocodbrestore.FieldWarnings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field warnings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Warnings); err != nil {
					return fmt.Errorf("unmarshal field warnings: %w", err)
				}
			}
		case nocodbrestore.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case nocodbrestore.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case nocodbrestore.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NocoDBRestore.
// This includes values selected through modifiers, order, etc.
func (_m *NocoDBRestore) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NocoDBRestore.
// Note that you need to call NocoDBRestore.Unwrap() before calling this method if this NocoDBRestore
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NocoDBRestore) Update() *NocoDBRestoreUpdateOne {
	return NewNocoDBRestoreClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NocoDBRestore entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NocoDBRestore) Unwrap() *NocoDBRestore {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NocoDBRestore is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NocoDBRestore) String() string {
	var builder strings.Builder
	builder.WriteString("NocoDBRestore(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("snapshot_id=")
	builder.WriteString(_m.SnapshotID)
	builder.WriteString(", ")
	builder.WriteString("source_connection_id=")
	builder.WriteString(_m.SourceConnectionID)
	builder.WriteString(", ")
	builder.WriteString("source_base_id=")
	builder.WriteString(_m.SourceBaseID)
	builder.WriteString(", ")
	builder.WriteString("source_base_title=")
	builder.WriteString(_m.SourceBaseTitle)
	builder.WriteString(", ")
	builder.WriteString("target_connection_id=")
	builder.WriteString(_m.TargetConnectionID)
	builder.WriteString(", ")
	builder.WriteString("target_base_id=")
	builder.WriteString(_m.TargetBaseID)
	builder.WriteString(", ")
	builder.WriteString("target_base_title=")
	builder.WriteString(_m.TargetBaseTitle)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(_m.Progress)
	builder.WriteString(", ")
	builder.WriteString("table_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TableCount))
	builder.WriteString(", ")
	builder.WriteString("record_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecordCount))
	builder.WriteString(", ")
	builder.WriteString("link_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.LinkCount))
	builder.WriteString(", ")
	builder.WriteString("file_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileCount))
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewCount))
	builder.WriteString(", ")
	builder.WriteString("hook_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.HookCount))
	builder.WriteString(", ")
	builder.WriteString("warnings=")
	builder.WriteString(fmt.Sprintf("%v", _m.Warnings))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NocoDBRestores is a parsable slice of NocoDBRestore.
type NocoDBRestores []*NocoDBRestore
