// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/nocodbbackuppolicy"
)

// NocoDBBackupPolicyCreate is the builder for creating a NocoDBBackupPolicy entity.
type NocoDBBackupPolicyCreate struct {
	config
	mutation *NocoDBBackupPolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConnectionID sets the "connection_id" field.
func (_c *NocoDBBackupPolicyCreate) SetConnectionID(v string) *NocoDBBackupPolicyCreate {
	_c.mutation.SetConnectionID(v)
	return _c
}

// SetBaseID sets the "base_id" field.
func (_c *NocoDBBackupPolicyCreate) SetBaseID(v string) *NocoDBBackupPolicyCreate {
	_c.mutation.SetBaseID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NocoDBBackupPolicyCreate) SetUserID(v string) *NocoDBBackupPolicyCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NocoDBBackupPolicyCreate) SetEnabled(v bool) *NocoDBBackupPolicyCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetCron sets the "cron" field.
func (_c *NocoDBBackupPolicyCreate) SetCron(v string) *NocoDBBackupPolicyCreate {
	_c.mutation.SetCron(v)
	return _c
}

// SetRetention sets the "retention" field.
func (_c *NocoDBBackupPolicyCreate) SetRetention(v int) *NocoDBBackupPolicyCreate {
	_c.mutation.SetRetention(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NocoDBBackupPolicyCreate) SetUpdatedAt(v time.Time) *NocoDBBackupPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the NocoDBBackupPolicyMutation object of the builder.
func (_c *NocoDBBackupPolicyCreate) Mutation() *NocoDBBackupPolicyMutation {
	return _c.mutation
}

// Save creates the NocoDBBackupPolicy in the database.
func (_c *NocoDBBackupPolicyCreate) Save(ctx context.Context) (*NocoDBBackupPolicy, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NocoDBBackupPolicyCreate) SaveX(ctx context.Context) *NocoDBBackupPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NocoDBBackupPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NocoDBBackupPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NocoDBBackupPolicyCreate) check() error {
	if _, ok := _c.mutation.ConnectionID(); !ok {
		return &ValidationError{Name: "connection_id", err: errors.New(`ent: missing required field "NocoDBBackupPolicy.connection_id"`)}
	}
	if _, ok := _c.mutation.BaseID(); !ok {
		return &ValidationError{Name: "base_id", err: errors.New(`ent: missing required field "NocoDBBackupPolicy.base_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NocoDBBackupPolicy.user_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NocoDBBackupPolicy.enabled"`)}
	}
	if _, ok := _c.mutation.Cron(); !ok {
		return &ValidationError{Name: "cron", err: errors.New(`ent: missing required field "NocoDBBackupPolicy.cron"`)}
	}
	if _, ok := _c.mutation.Retention(); !ok {
		return &ValidationError{Name: "retention", err: errors.New(`ent: missing required field "NocoDBBackupPolicy.retention"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NocoDBBackupPolicy.updated_at"`)}
	}
	return nil
}

func (_c *NocoDBBackupPolicyCreate) sqlSave(ctx context.Context) (*NocoDBBackupPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NocoDBBackupPolicyCreate) createSpec() (*NocoDBBackupPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &NocoDBBackupPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nocodbbackuppolicy.Table, sqlgraph.NewFieldSpec(nocodbbackuppolicy.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ConnectionID(); ok {
		_spec.SetField(nocodbbackuppolicy.FieldConnectionID, field.TypeString, value)
		_node.ConnectionID = value
	}
	if value, ok := _c.mutation.BaseID(); ok {
		_spec.SetField(nocodbbackuppolicy.FieldBaseID, field.TypeString, value)
		_node.BaseID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(nocodbbackuppolicy.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(nocodbbackuppolicy.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Cron(); ok {
		_spec.SetField(nocodbbackuppolicy.FieldCron, field.TypeString, value)
		_node.Cron = value
	}
	if value, ok := _c.mutation.Retention(); ok {
		_spec.SetField(nocodbbackuppolicy.FieldRetention, field.TypeInt, value)
		_node.Retention = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(nocodbbackuppolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NocoDBBackupPolicy.Create().
//		SetConnectionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NocoDBBackupPolicyUpsert) {
//			SetConnectionID(v+v).
//		}).
//		Exec(ctx)
func (_c *NocoDBBackupPolicyCreate) OnConflict(opts ...sql.ConflictOption) *NocoDBBackupPolicyUpsertOne {
	_c.conflict = opts
	return &NocoDBBackupPolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NocoDBBackupPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NocoDBBackupPolicyCreate) OnConflictColumns(columns ...string) *NocoDBBackupPolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NocoDBBackupPolicyUpsertOne{
		create: _c,
	}
}

type (
	// NocoDBBackupPolicyUpsertOne is the builder for "upsert"-ing
	//  one NocoDBBackupPolicy node.
	NocoDBBackupPolicyUpsertOne struct {
		create *NocoDBBackupPolicyCreate
	}

	// NocoDBBackupPolicyUpsert is the "OnConflict" setter.
	NocoDBBackupPolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetEnabled sets the "enabled" field.
func (u *NocoDBBackupPolicyUpsert) SetEnabled(v bool) *NocoDBBackupPolicyUpsert {
	u.Set(nocodbbackuppolicy.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsert) UpdateEnabled() *NocoDBBackupPolicyUpsert {
	u.SetExcluded(nocodbbackuppolicy.FieldEnabled)
	return u
}

// SetCron sets the "cron" field.
func (u *NocoDBBackupPolicyUpsert) SetCron(v string) *NocoDBBackupPolicyUpsert {
	u.Set(nocodbbackuppolicy.FieldCron, v)
	return u
}

// UpdateCron sets the "cron" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsert) UpdateCron() *NocoDBBackupPolicyUpsert {
	u.SetExcluded(nocodbbackuppolicy.FieldCron)
	return u
}

// SetRetention sets the "retention" field.
func (u *NocoDBBackupPolicyUpsert) SetRetention(v int) *NocoDBBackupPolicyUpsert {
	u.Set(nocodbbackuppolicy.FieldRetention, v)
	return u
}

// UpdateRetention sets the "retention" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsert) UpdateRetention() *NocoDBBackupPolicyUpsert {
	u.SetExcluded(nocodbbackuppolicy.FieldRetention)
	return u
}

// AddRetention adds v to the "retention" field.
func (u *NocoDBBackupPolicyUpsert) AddRetention(v int) *NocoDBBackupPolicyUpsert {
	u.Add(nocodbbackuppolicy.FieldRetention, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NocoDBBackupPolicyUpsert) SetUpdatedAt(v time.Time) *NocoDBBackupPolicyUpsert {
	u.Set(nocodbbackuppolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsert) UpdateUpdatedAt() *NocoDBBackupPolicyUpsert {
	u.SetExcluded(nocodbbackuppolicy.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NocoDBBackupPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NocoDBBackupPolicyUpsertOne) UpdateNewValues() *NocoDBBackupPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ConnectionID(); exists {
			s.SetIgnore(nocodbbackuppolicy.FieldConnectionID)
		}
		if _, exists := u.create.mutation.BaseID(); exists {
			s.SetIgnore(nocodbbackuppolicy.FieldBaseID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(nocodbbackuppolicy.FieldUserID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NocoDBBackupPolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NocoDBBackupPolicyUpsertOne) Ignore() *NocoDBBackupPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NocoDBBackupPolicyUpsertOne) DoNothing() *NocoDBBackupPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NocoDBBackupPolicyCreate.OnConflict
// documentation for more info.
func (u *NocoDBBackupPolicyUpsertOne) Update(set func(*NocoDBBackupPolicyUpsert)) *NocoDBBackupPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NocoDBBackupPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetEnabled sets the "enabled" field.
func (u *NocoDBBackupPolicyUpsertOne) SetEnabled(v bool) *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsertOne) UpdateEnabled() *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.UpdateEnabled()
	})
}

// SetCron sets the "cron" field.
func (u *NocoDBBackupPolicyUpsertOne) SetCron(v string) *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.SetCron(v)
	})
}

// UpdateCron sets the "cron" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsertOne) UpdateCron() *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.UpdateCron()
	})
}

// SetRetention sets the "retention" field.
func (u *NocoDBBackupPolicyUpsertOne) SetRetention(v int) *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.SetRetention(v)
	})
}

// AddRetention adds v to the "retention" field.
func (u *NocoDBBackupPolicyUpsertOne) AddRetention(v int) *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.AddRetention(v)
	})
}

// UpdateRetention sets the "retention" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsertOne) UpdateRetention() *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.UpdateRetention()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NocoDBBackupPolicyUpsertOne) SetUpdatedAt(v time.Time) *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsertOne) UpdateUpdatedAt() *NocoDBBackupPolicyUpsertOne {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NocoDBBackupPolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NocoDBBackupPolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NocoDBBackupPolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NocoDBBackupPolicyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NocoDBBackupPolicyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NocoDBBackupPolicyCreateBulk is the builder for creating many NocoDBBackupPolicy entities in bulk.
type NocoDBBackupPolicyCreateBulk struct {
	config
	err      error
	builders []*NocoDBBackupPolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the NocoDBBackupPolicy entities in the database.
func (_c *NocoDBBackupPolicyCreateBulk) Save(ctx context.Context) ([]*NocoDBBackupPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NocoDBBackupPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NocoDBBackupPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NocoDBBackupPolicyCreateBulk) SaveX(ctx context.Context) []*NocoDBBackupPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NocoDBBackupPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NocoDBBackupPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NocoDBBackupPolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NocoDBBackupPolicyUpsert) {
//			SetConnectionID(v+v).
//		}).
//		Exec(ctx)
func (_c *NocoDBBackupPolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *NocoDBBackupPolicyUpsertBulk {
	_c.conflict = opts
	return &NocoDBBackupPolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NocoDBBackupPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NocoDBBackupPolicyCreateBulk) OnConflictColumns(columns ...string) *NocoDBBackupPolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NocoDBBackupPolicyUpsertBulk{
		create: _c,
	}
}

// NocoDBBackupPolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of NocoDBBackupPolicy nodes.
type NocoDBBackupPolicyUpsertBulk struct {
	create *NocoDBBackupPolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NocoDBBackupPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NocoDBBackupPolicyUpsertBulk) UpdateNewValues() *NocoDBBackupPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ConnectionID(); exists {
				s.SetIgnore(nocodbbackuppolicy.FieldConnectionID)
			}
			if _, exists := b.mutation.BaseID(); exists {
				s.SetIgnore(nocodbbackuppolicy.FieldBaseID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(nocodbbackuppolicy.FieldUserID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NocoDBBackupPolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NocoDBBackupPolicyUpsertBulk) Ignore() *NocoDBBackupPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NocoDBBackupPolicyUpsertBulk) DoNothing() *NocoDBBackupPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NocoDBBackupPolicyCreateBulk.OnConflict
// documentation for more info.
func (u *NocoDBBackupPolicyUpsertBulk) Update(set func(*NocoDBBackupPolicyUpsert)) *NocoDBBackupPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NocoDBBackupPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetEnabled sets the "enabled" field.
func (u *NocoDBBackupPolicyUpsertBulk) SetEnabled(v bool) *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsertBulk) UpdateEnabled() *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.UpdateEnabled()
	})
}

// SetCron sets the "cron" field.
func (u *NocoDBBackupPolicyUpsertBulk) SetCron(v string) *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.SetCron(v)
	})
}

// UpdateCron sets the "cron" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsertBulk) UpdateCron() *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.UpdateCron()
	})
}

// SetRetention sets the "retention" field.
func (u *NocoDBBackupPolicyUpsertBulk) SetRetention(v int) *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.SetRetention(v)
	})
}

// AddRetention adds v to the "retention" field.
func (u *NocoDBBackupPolicyUpsertBulk) AddRetention(v int) *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.AddRetention(v)
	})
}

// UpdateRetention sets the "retention" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsertBulk) UpdateRetention() *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.UpdateRetention()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NocoDBBackupPolicyUpsertBulk) SetUpdatedAt(v time.Time) *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NocoDBBackupPolicyUpsertBulk) UpdateUpdatedAt() *NocoDBBackupPolicyUpsertBulk {
	return u.Update(func(s *NocoDBBackupPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NocoDBBackupPolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NocoDBBackupPolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NocoDBBackupPolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NocoDBBackupPolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
