// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/nocodbfilesource"
)

// NocoDBFileSourceCreate is the builder for creating a NocoDBFileSource entity.
type NocoDBFileSourceCreate struct {
	config
	mutation *NocoDBFileSourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConnectionID sets the "connection_id" field.
func (_c *NocoDBFileSourceCreate) SetConnectionID(v string) *NocoDBFileSourceCreate {
	_c.mutation.SetConnectionID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *NocoDBFileSourceCreate) SetSource(v string) *NocoDBFileSourceCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *NocoDBFileSourceCreate) SetSize(v int64) *NocoDBFileSourceCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *NocoDBFileSourceCreate) SetSha256(v string) *NocoDBFileSourceCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// Mutation returns the NocoDBFileSourceMutation object of the builder.
func (_c *NocoDBFileSourceCreate) Mutation() *NocoDBFileSourceMutation {
	return _c.mutation
}

// Save creates the NocoDBFileSource in the database.
func (_c *NocoDBFileSourceCreate) Save(ctx context.Context) (*NocoDBFileSource, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NocoDBFileSourceCreate) SaveX(ctx context.Context) *NocoDBFileSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NocoDBFileSourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NocoDBFileSourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NocoDBFileSourceCreate) check() error {
	if _, ok := _c.mutation.ConnectionID(); !ok {
		return &ValidationError{Name: "connection_id", err: errors.New(`ent: missing required field "NocoDBFileSource.connection_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "NocoDBFileSource.source"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "NocoDBFileSource.size"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "NocoDBFileSource.sha256"`)}
	}
	return nil
}

func (_c *NocoDBFileSourceCreate) sqlSave(ctx context.Context) (*NocoDBFileSource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NocoDBFileSourceCreate) createSpec() (*NocoDBFileSource, *sqlgraph.CreateSpec) {
	var (
		_node = &NocoDBFileSource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nocodbfilesource.Table, sqlgraph.NewFieldSpec(nocodbfilesource.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ConnectionID(); ok {
		_spec.SetField(nocodbfilesource.FieldConnectionID, field.TypeString, value)
		_node.ConnectionID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(nocodbfilesource.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(nocodbfilesource.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(nocodbfilesource.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NocoDBFileSource.Create().
//		SetConnectionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NocoDBFileSourceUpsert) {
//			SetConnectionID(v+v).
//		}).
//		Exec(ctx)
func (_c *NocoDBFileSourceCreate) OnConflict(opts ...sql.ConflictOption) *NocoDBFileSourceUpsertOne {
	_c.conflict = opts
	return &NocoDBFileSourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NocoDBFileSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NocoDBFileSourceCreate) OnConflictColumns(columns ...string) *NocoDBFileSourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NocoDBFileSourceUpsertOne{
		create: _c,
	}
}

type (
	// NocoDBFileSourceUpsertOne is the builder for "upsert"-ing
	//  one NocoDBFileSource node.
	NocoDBFileSourceUpsertOne struct {
		create *NocoDBFileSourceCreate
	}

	// NocoDBFileSourceUpsert is the "OnConflict" setter.
	NocoDBFileSourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetSha256 sets the "sha256" field.
func (u *NocoDBFileSourceUpsert) SetSha256(v string) *NocoDBFileSourceUpsert {
	u.Set(nocodbfilesource.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *NocoDBFileSourceUpsert) UpdateSha256() *NocoDBFileSourceUpsert {
	u.SetExcluded(nocodbfilesource.FieldSha256)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NocoDBFileSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NocoDBFileSourceUpsertOne) UpdateNewValues() *NocoDBFileSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ConnectionID(); exists {
			s.SetIgnore(nocodbfilesource.FieldConnectionID)
		}
		if _, exists := u.create.mutation.Source(); exists {
			s.SetIgnore(nocodbfilesource.FieldSource)
		}
		if _, exists := u.create.mutation.Size(); exists {
			s.SetIgnore(nocodbfilesource.FieldSize)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NocoDBFileSource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NocoDBFileSourceUpsertOne) Ignore() *NocoDBFileSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NocoDBFileSourceUpsertOne) DoNothing() *NocoDBFileSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NocoDBFileSourceCreate.OnConflict
// documentation for more info.
func (u *NocoDBFileSourceUpsertOne) Update(set func(*NocoDBFileSourceUpsert)) *NocoDBFileSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NocoDBFileSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetSha256 sets the "sha256" field.
func (u *NocoDBFileSourceUpsertOne) SetSha256(v string) *NocoDBFileSourceUpsertOne {
	return u.Update(func(s *NocoDBFileSourceUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *NocoDBFileSourceUpsertOne) UpdateSha256() *NocoDBFileSourceUpsertOne {
	return u.Update(func(s *NocoDBFileSourceUpsert) {
		s.UpdateSha256()
	})
}

// Exec executes the query.
func (u *NocoDBFileSourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NocoDBFileSourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NocoDBFileSourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NocoDBFileSourceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NocoDBFileSourceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NocoDBFileSourceCreateBulk is the builder for creating many NocoDBFileSource entities in bulk.
type NocoDBFileSourceCreateBulk struct {
	config
	err      error
	builders []*NocoDBFileSourceCreate
	conflict []sql.ConflictOption
}

// Save creates the NocoDBFileSource entities in the database.
func (_c *NocoDBFileSourceCreateBulk) Save(ctx context.Context) ([]*NocoDBFileSource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NocoDBFileSource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NocoDBFileSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NocoDBFileSourceCreateBulk) SaveX(ctx context.Context) []*NocoDBFileSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NocoDBFileSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NocoDBFileSourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NocoDBFileSource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NocoDBFileSourceUpsert) {
//			SetConnectionID(v+v).
//		}).
//		Exec(ctx)
func (_c *NocoDBFileSourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *NocoDBFileSourceUpsertBulk {
	_c.conflict = opts
	return &NocoDBFileSourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NocoDBFileSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NocoDBFileSourceCreateBulk) OnConflictColumns(columns ...string) *NocoDBFileSourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NocoDBFileSourceUpsertBulk{
		create: _c,
	}
}

// NocoDBFileSourceUpsertBulk is the builder for "upsert"-ing
// a bulk of NocoDBFileSource nodes.
type NocoDBFileSourceUpsertBulk struct {
	create *NocoDBFileSourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NocoDBFileSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NocoDBFileSourceUpsertBulk) UpdateNewValues() *NocoDBFileSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ConnectionID(); exists {
				s.SetIgnore(nocodbfilesource.FieldConnectionID)
			}
			if _, exists := b.mutation.Source(); exists {
				s.SetIgnore(nocodbfilesource.FieldSource)
			}
			if _, exists := b.mutation.Size(); exists {
				s.SetIgnore(nocodbfilesource.FieldSize)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NocoDBFileSource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NocoDBFileSourceUpsertBulk) Ignore() *NocoDBFileSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NocoDBFileSourceUpsertBulk) DoNothing() *NocoDBFileSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NocoDBFileSourceCreateBulk.OnConflict
// documentation for more info.
func (u *NocoDBFileSourceUpsertBulk) Update(set func(*NocoDBFileSourceUpsert)) *NocoDBFileSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NocoDBFileSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetSha256 sets the "sha256" field.
func (u *NocoDBFileSourceUpsertBulk) SetSha256(v string) *NocoDBFileSourceUpsertBulk {
	return u.Update(func(s *NocoDBFileSourceUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *NocoDBFileSourceUpsertBulk) UpdateSha256() *NocoDBFileSourceUpsertBulk {
	return u.Update(func(s *NocoDBFileSourceUpsert) {
		s.UpdateSha256()
	})
}

// Exec executes the query.
func (u *NocoDBFileSourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NocoDBFileSourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NocoDBFileSourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NocoDBFileSourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
