// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/nocodbsnapshotfile"
)

// NocoDBSnapshotFileCreate is the builder for creating a NocoDBSnapshotFile entity.
type NocoDBSnapshotFileCreate struct {
	config
	mutation *NocoDBSnapshotFileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSnapshotID sets the "snapshot_id" field.
func (_c *NocoDBSnapshotFileCreate) SetSnapshotID(v string) *NocoDBSnapshotFileCreate {
	_c.mutation.SetSnapshotID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NocoDBSnapshotFileCreate) SetUserID(v string) *NocoDBSnapshotFileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *NocoDBSnapshotFileCreate) SetSha256(v string) *NocoDBSnapshotFileCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// Mutation returns the NocoDBSnapshotFileMutation object of the builder.
func (_c *NocoDBSnapshotFileCreate) Mutation() *NocoDBSnapshotFileMutation {
	return _c.mutation
}

// Save creates the NocoDBSnapshotFile in the database.
func (_c *NocoDBSnapshotFileCreate) Save(ctx context.Context) (*NocoDBSnapshotFile, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NocoDBSnapshotFileCreate) SaveX(ctx context.Context) *NocoDBSnapshotFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NocoDBSnapshotFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NocoDBSnapshotFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NocoDBSnapshotFileCreate) check() error {
	if _, ok := _c.mutation.SnapshotID(); !ok {
		return &ValidationError{Name: "snapshot_id", err: errors.New(`ent: missing required field "NocoDBSnapshotFile.snapshot_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NocoDBSnapshotFile.user_id"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "NocoDBSnapshotFile.sha256"`)}
	}
	return nil
}

func (_c *NocoDBSnapshotFileCreate) sqlSave(ctx context.Context) (*NocoDBSnapshotFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NocoDBSnapshotFileCreate) createSpec() (*NocoDBSnapshotFile, *sqlgraph.CreateSpec) {
	var (
		_node = &NocoDBSnapshotFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nocodbsnapshotfile.Table, sqlgraph.NewFieldSpec(nocodbsnapshotfile.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SnapshotID(); ok {
		_spec.SetField(nocodbsnapshotfile.FieldSnapshotID, field.TypeString, value)
		_node.SnapshotID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(nocodbsnapshotfile.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(nocodbsnapshotfile.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NocoDBSnapshotFile.Create().
//		SetSnapshotID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NocoDBSnapshotFileUpsert) {
//			SetSnapshotID(v+v).
//		}).
//		Exec(ctx)
func (_c *NocoDBSnapshotFileCreate) OnConflict(opts ...sql.ConflictOption) *NocoDBSnapshotFileUpsertOne {
	_c.conflict = opts
	return &NocoDBSnapshotFileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NocoDBSnapshotFile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NocoDBSnapshotFileCreate) OnConflictColumns(columns ...string) *NocoDBSnapshotFileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NocoDBSnapshotFileUpsertOne{
		create: _c,
	}
}

type (
	// NocoDBSnapshotFileUpsertOne is the builder for "upsert"-ing
	//  one NocoDBSnapshotFile node.
	NocoDBSnapshotFileUpsertOne struct {
		create *NocoDBSnapshotFileCreate
	}

	// NocoDBSnapshotFileUpsert is the "OnConflict" setter.
	NocoDBSnapshotFileUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NocoDBSnapshotFile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NocoDBSnapshotFileUpsertOne) UpdateNewValues() *NocoDBSnapshotFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.SnapshotID(); exists {
			s.SetIgnore(nocodbsnapshotfile.FieldSnapshotID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(nocodbsnapshotfile.FieldUserID)
		}
		if _, exists := u.create.mutation.Sha256(); exists {
			s.SetIgnore(nocodbsnapshotfile.FieldSha256)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NocoDBSnapshotFile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NocoDBSnapshotFileUpsertOne) Ignore() *NocoDBSnapshotFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NocoDBSnapshotFileUpsertOne) DoNothing() *NocoDBSnapshotFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NocoDBSnapshotFileCreate.OnConflict
// documentation for more info.
func (u *NocoDBSnapshotFileUpsertOne) Update(set func(*NocoDBSnapshotFileUpsert)) *NocoDBSnapshotFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NocoDBSnapshotFileUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *NocoDBSnapshotFileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NocoDBSnapshotFileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NocoDBSnapshotFileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NocoDBSnapshotFileUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NocoDBSnapshotFileUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NocoDBSnapshotFileCreateBulk is the builder for creating many NocoDBSnapshotFile entities in bulk.
type NocoDBSnapshotFileCreateBulk struct {
	config
	err      error
	builders []*NocoDBSnapshotFileCreate
	conflict []sql.ConflictOption
}

// Save creates the NocoDBSnapshotFile entities in the database.
func (_c *NocoDBSnapshotFileCreateBulk) Save(ctx context.Context) ([]*NocoDBSnapshotFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NocoDBSnapshotFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NocoDBSnapshotFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NocoDBSnapshotFileCreateBulk) SaveX(ctx context.Context) []*NocoDBSnapshotFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NocoDBSnapshotFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NocoDBSnapshotFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NocoDBSnapshotFile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NocoDBSnapshotFileUpsert) {
//			SetSnapshotID(v+v).
//		}).
//		Exec(ctx)
func (_c *NocoDBSnapshotFileCreateBulk) OnConflict(opts ...sql.ConflictOption) *NocoDBSnapshotFileUpsertBulk {
	_c.conflict = opts
	return &NocoDBSnapshotFileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NocoDBSnapshotFile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NocoDBSnapshotFileCreateBulk) OnConflictColumns(columns ...string) *NocoDBSnapshotFileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NocoDBSnapshotFileUpsertBulk{
		create: _c,
	}
}

// NocoDBSnapshotFileUpsertBulk is the builder for "upsert"-ing
// a bulk of NocoDBSnapshotFile nodes.
type NocoDBSnapshotFileUpsertBulk struct {
	create *NocoDBSnapshotFileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NocoDBSnapshotFile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NocoDBSnapshotFileUpsertBulk) UpdateNewValues() *NocoDBSnapshotFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.SnapshotID(); exists {
				s.SetIgnore(nocodbsnapshotfile.FieldSnapshotID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(nocodbsnapshotfile.FieldUserID)
			}
			if _, exists := b.mutation.Sha256(); exists {
				s.SetIgnore(nocodbsnapshotfile.FieldSha256)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NocoDBSnapshotFile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NocoDBSnapshotFileUpsertBulk) Ignore() *NocoDBSnapshotFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NocoDBSnapshotFileUpsertBulk) DoNothing() *NocoDBSnapshotFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NocoDBSnapshotFileCreateBulk.OnConflict
// documentation for more info.
func (u *NocoDBSnapshotFileUpsertBulk) Update(set func(*NocoDBSnapshotFileUpsert)) *NocoDBSnapshotFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NocoDBSnapshotFileUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *NocoDBSnapshotFileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NocoDBSnapshotFileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NocoDBSnapshotFileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NocoDBSnapshotFileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
