// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/nocodbrestore"
	"go.orx.me/apps/neo-box/internal/ent/predicate"
	"go.orx.me/apps/neo-box/internal/repo/nocodb"
)

// NocoDBRestoreUpdate is the builder for updating NocoDBRestore entities.
type NocoDBRestoreUpdate struct {
	config
	hooks    []Hook
	mutation *NocoDBRestoreMutation
}

// Where appends a list predicates to the NocoDBRestoreUpdate builder.
func (_u *NocoDBRestoreUpdate) Where(ps ...predicate.NocoDBRestore) *NocoDBRestoreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTargetBaseID sets the "target_base_id" field.
func (_u *NocoDBRestoreUpdate) SetTargetBaseID(v string) *NocoDBRestoreUpdate {
	_u.mutation.SetTargetBaseID(v)
	return _u
}

// SetNillableTargetBaseID sets the "target_base_id" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableTargetBaseID(v *string) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetTargetBaseID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NocoDBRestoreUpdate) SetStatus(v string) *NocoDBRestoreUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableStatus(v *string) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *NocoDBRestoreUpdate) SetError(v string) *NocoDBRestoreUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableError(v *string) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetProgress sets the "progress" field.
func (_u *NocoDBRestoreUpdate) SetProgress(v string) *NocoDBRestoreUpdate {
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableProgress(v *string) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// SetTableCount sets the "table_count" field.
func (_u *NocoDBRestoreUpdate) SetTableCount(v int) *NocoDBRestoreUpdate {
	_u.mutation.ResetTableCount()
	_u.mutation.SetTableCount(v)
	return _u
}

// SetNillableTableCount sets the "table_count" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableTableCount(v *int) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetTableCount(*v)
	}
	return _u
}

// AddTableCount adds value to the "table_count" field.
func (_u *NocoDBRestoreUpdate) AddTableCount(v int) *NocoDBRestoreUpdate {
	_u.mutation.AddTableCount(v)
	return _u
}

// SetRecordCount sets the "record_count" field.
func (_u *NocoDBRestoreUpdate) SetRecordCount(v int64) *NocoDBRestoreUpdate {
	_u.mutation.ResetRecordCount()
	_u.mutation.SetRecordCount(v)
	return _u
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableRecordCount(v *int64) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetRecordCount(*v)
	}
	return _u
}

// AddRecordCount adds value to the "record_count" field.
func (_u *NocoDBRestoreUpdate) AddRecordCount(v int64) *NocoDBRestoreUpdate {
	_u.mutation.AddRecordCount(v)
	return _u
}

// SetLinkCount sets the "link_count" field.
func (_u *NocoDBRestoreUpdate) SetLinkCount(v int64) *NocoDBRestoreUpdate {
	_u.mutation.ResetLinkCount()
	_u.mutation.SetLinkCount(v)
	return _u
}

// SetNillableLinkCount sets the "link_count" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableLinkCount(v *int64) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetLinkCount(*v)
	}
	return _u
}

// AddLinkCount adds value to the "link_count" field.
func (_u *NocoDBRestoreUpdate) AddLinkCount(v int64) *NocoDBRestoreUpdate {
	_u.mutation.AddLinkCount(v)
	return _u
}

// SetWarnings sets the "warnings" field.
func (_u *NocoDBRestoreUpdate) SetWarnings(v []nocodb.RestoreWarning) *NocoDBRestoreUpdate {
	_u.mutation.SetWarnings(v)
	return _u
}

// AppendWarnings appends value to the "warnings" field.
func (_u *NocoDBRestoreUpdate) AppendWarnings(v []nocodb.RestoreWarning) *NocoDBRestoreUpdate {
	_u.mutation.AppendWarnings(v)
	return _u
}

// ClearWarnings clears the value of the "warnings" field.
func (_u *NocoDBRestoreUpdate) ClearWarnings() *NocoDBRestoreUpdate {
	_u.mutation.ClearWarnings()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *NocoDBRestoreUpdate) SetStartedAt(v time.Time) *NocoDBRestoreUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableStartedAt(v *time.Time) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *NocoDBRestoreUpdate) ClearStartedAt() *NocoDBRestoreUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *NocoDBRestoreUpdate) SetFinishedAt(v time.Time) *NocoDBRestoreUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *NocoDBRestoreUpdate) SetNillableFinishedAt(v *time.Time) *NocoDBRestoreUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *NocoDBRestoreUpdate) ClearFinishedAt() *NocoDBRestoreUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the NocoDBRestoreMutation object of the builder.
func (_u *NocoDBRestoreUpdate) Mutation() *NocoDBRestoreMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NocoDBRestoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NocoDBRestoreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NocoDBRestoreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NocoDBRestoreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NocoDBRestoreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(nocodbrestore.Table, nocodbrestore.Columns, sqlgraph.NewFieldSpec(nocodbrestore.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetBaseID(); ok {
		_spec.SetField(nocodbrestore.FieldTargetBaseID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(nocodbrestore.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(nocodbrestore.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(nocodbrestore.FieldProgress, field.TypeString, value)
	}
	if value, ok := _u.mutation.TableCount(); ok {
		_spec.SetField(nocodbrestore.FieldTableCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTableCount(); ok {
		_spec.AddField(nocodbrestore.FieldTableCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecordCount(); ok {
		_spec.SetField(nocodbrestore.FieldRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordCount(); ok {
		_spec.AddField(nocodbrestore.FieldRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LinkCount(); ok {
		_spec.SetField(nocodbrestore.FieldLinkCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLinkCount(); ok {
		_spec.AddField(nocodbrestore.FieldLinkCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Warnings(); ok {
		_spec.SetField(nocodbrestore.FieldWarnings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWarnings(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, nocodbrestore.FieldWarnings, value)
		})
	}
	if _u.mutation.WarningsCleared() {
		_spec.ClearField(nocodbrestore.FieldWarnings, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(nocodbrestore.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(nocodbrestore.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(nocodbrestore.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(nocodbrestore.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nocodbrestore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NocoDBRestoreUpdateOne is the builder for updating a single NocoDBRestore entity.
type NocoDBRestoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NocoDBRestoreMutation
}

// SetTargetBaseID sets the "target_base_id" field.
func (_u *NocoDBRestoreUpdateOne) SetTargetBaseID(v string) *NocoDBRestoreUpdateOne {
	_u.mutation.SetTargetBaseID(v)
	return _u
}

// SetNillableTargetBaseID sets the "target_base_id" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableTargetBaseID(v *string) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetTargetBaseID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NocoDBRestoreUpdateOne) SetStatus(v string) *NocoDBRestoreUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableStatus(v *string) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *NocoDBRestoreUpdateOne) SetError(v string) *NocoDBRestoreUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableError(v *string) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetProgress sets the "progress" field.
func (_u *NocoDBRestoreUpdateOne) SetProgress(v string) *NocoDBRestoreUpdateOne {
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableProgress(v *string) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// SetTableCount sets the "table_count" field.
func (_u *NocoDBRestoreUpdateOne) SetTableCount(v int) *NocoDBRestoreUpdateOne {
	_u.mutation.ResetTableCount()
	_u.mutation.SetTableCount(v)
	return _u
}

// SetNillableTableCount sets the "table_count" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableTableCount(v *int) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetTableCount(*v)
	}
	return _u
}

// AddTableCount adds value to the "table_count" field.
func (_u *NocoDBRestoreUpdateOne) AddTableCount(v int) *NocoDBRestoreUpdateOne {
	_u.mutation.AddTableCount(v)
	return _u
}

// SetRecordCount sets the "record_count" field.
func (_u *NocoDBRestoreUpdateOne) SetRecordCount(v int64) *NocoDBRestoreUpdateOne {
	_u.mutation.ResetRecordCount()
	_u.mutation.SetRecordCount(v)
	return _u
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableRecordCount(v *int64) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetRecordCount(*v)
	}
	return _u
}

// AddRecordCount adds value to the "record_count" field.
func (_u *NocoDBRestoreUpdateOne) AddRecordCount(v int64) *NocoDBRestoreUpdateOne {
	_u.mutation.AddRecordCount(v)
	return _u
}

// SetLinkCount sets the "link_count" field.
func (_u *NocoDBRestoreUpdateOne) SetLinkCount(v int64) *NocoDBRestoreUpdateOne {
	_u.mutation.ResetLinkCount()
	_u.mutation.SetLinkCount(v)
	return _u
}

// SetNillableLinkCount sets the "link_count" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableLinkCount(v *int64) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetLinkCount(*v)
	}
	return _u
}

// AddLinkCount adds value to the "link_count" field.
func (_u *NocoDBRestoreUpdateOne) AddLinkCount(v int64) *NocoDBRestoreUpdateOne {
	_u.mutation.AddLinkCount(v)
	return _u
}

// SetWarnings sets the "warnings" field.
func (_u *NocoDBRestoreUpdateOne) SetWarnings(v []nocodb.RestoreWarning) *NocoDBRestoreUpdateOne {
	_u.mutation.SetWarnings(v)
	return _u
}

// AppendWarnings appends value to the "warnings" field.
func (_u *NocoDBRestoreUpdateOne) AppendWarnings(v []nocodb.RestoreWarning) *NocoDBRestoreUpdateOne {
	_u.mutation.AppendWarnings(v)
	return _u
}

// ClearWarnings clears the value of the "warnings" field.
func (_u *NocoDBRestoreUpdateOne) ClearWarnings() *NocoDBRestoreUpdateOne {
	_u.mutation.ClearWarnings()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *NocoDBRestoreUpdateOne) SetStartedAt(v time.Time) *NocoDBRestoreUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableStartedAt(v *time.Time) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *NocoDBRestoreUpdateOne) ClearStartedAt() *NocoDBRestoreUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *NocoDBRestoreUpdateOne) SetFinishedAt(v time.Time) *NocoDBRestoreUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *NocoDBRestoreUpdateOne) SetNillableFinishedAt(v *time.Time) *NocoDBRestoreUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *NocoDBRestoreUpdateOne) ClearFinishedAt() *NocoDBRestoreUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the NocoDBRestoreMutation object of the builder.
func (_u *NocoDBRestoreUpdateOne) Mutation() *NocoDBRestoreMutation {
	return _u.mutation
}

// Where appends a list predicates to the NocoDBRestoreUpdate builder.
func (_u *NocoDBRestoreUpdateOne) Where(ps ...predicate.NocoDBRestore) *NocoDBRestoreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NocoDBRestoreUpdateOne) Select(field string, fields ...string) *NocoDBRestoreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NocoDBRestore entity.
func (_u *NocoDBRestoreUpdateOne) Save(ctx context.Context) (*NocoDBRestore, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NocoDBRestoreUpdateOne) SaveX(ctx context.Context) *NocoDBRestore {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NocoDBRestoreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NocoDBRestoreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NocoDBRestoreUpdateOne) sqlSave(ctx context.Context) (_node *NocoDBRestore, err error) {
	_spec := sqlgraph.NewUpdateSpec(nocodbrestore.Table, nocodbrestore.Columns, sqlgraph.NewFieldSpec(nocodbrestore.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NocoDBRestore.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nocodbrestore.FieldID)
		for _, f := range fields {
			if !nocodbrestore.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nocodbrestore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetBaseID(); ok {
		_spec.SetField(nocodbrestore.FieldTargetBaseID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(nocodbrestore.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(nocodbrestore.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(nocodbrestore.FieldProgress, field.TypeString, value)
	}
	if value, ok := _u.mutation.TableCount(); ok {
		_spec.SetField(nocodbrestore.FieldTableCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTableCount(); ok {
		_spec.AddField(nocodbrestore.FieldTableCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecordCount(); ok {
		_spec.SetField(nocodbrestore.FieldRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordCount(); ok {
		_spec.AddField(nocodbrestore.FieldRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LinkCount(); ok {
		_spec.SetField(nocodbrestore.FieldLinkCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLinkCount(); ok {
		_spec.AddField(nocodbrestore.FieldLinkCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Warnings(); ok {
		_spec.SetField(nocodbrestore.FieldWarnings, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWarnings(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, nocodbrestore.FieldWarnings, value)
		})
	}
	if _u.mutation.WarningsCleared() {
		_spec.ClearField(nocodbrestore.FieldWarnings, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(nocodbrestore.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(nocodbrestore.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(nocodbrestore.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(nocodbrestore.FieldFinishedAt, field.TypeTime)
	}
	_node = &NocoDBRestore{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nocodbrestore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
