// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/nocodbbackuppolicy"
	"go.orx.me/apps/neo-box/internal/ent/predicate"
)

// NocoDBBackupPolicyDelete is the builder for deleting a NocoDBBackupPolicy entity.
type NocoDBBackupPolicyDelete struct {
	config
	hooks    []Hook
	mutation *NocoDBBackupPolicyMutation
}

// Where appends a list predicates to the NocoDBBackupPolicyDelete builder.
func (_d *NocoDBBackupPolicyDelete) Where(ps ...predicate.NocoDBBackupPolicy) *NocoDBBackupPolicyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NocoDBBackupPolicyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NocoDBBackupPolicyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NocoDBBackupPolicyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nocodbbackuppolicy.Table, sqlgraph.NewFieldSpec(nocodbbackuppolicy.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NocoDBBackupPolicyDeleteOne is the builder for deleting a single NocoDBBackupPolicy entity.
type NocoDBBackupPolicyDeleteOne struct {
	_d *NocoDBBackupPolicyDelete
}

// Where appends a list predicates to the NocoDBBackupPolicyDelete builder.
func (_d *NocoDBBackupPolicyDeleteOne) Where(ps ...predicate.NocoDBBackupPolicy) *NocoDBBackupPolicyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NocoDBBackupPolicyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nocodbbackuppolicy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NocoDBBackupPolicyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
