// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/nocodbrestore"
	"go.orx.me/apps/neo-box/internal/repo/nocodb"
)

// NocoDBRestoreCreate is the builder for creating a NocoDBRestore entity.
type NocoDBRestoreCreate struct {
	config
	mutation *NocoDBRestoreMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *NocoDBRestoreCreate) SetUserID(v string) *NocoDBRestoreCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSnapshotID sets the "snapshot_id" field.
func (_c *NocoDBRestoreCreate) SetSnapshotID(v string) *NocoDBRestoreCreate {
	_c.mutation.SetSnapshotID(v)
	return _c
}

// SetSourceConnectionID sets the "source_connection_id" field.
func (_c *NocoDBRestoreCreate) SetSourceConnectionID(v string) *NocoDBRestoreCreate {
	_c.mutation.SetSourceConnectionID(v)
	return _c
}

// SetSourceBaseID sets the "source_base_id" field.
func (_c *NocoDBRestoreCreate) SetSourceBaseID(v string) *NocoDBRestoreCreate {
	_c.mutation.SetSourceBaseID(v)
	return _c
}

// SetSourceBaseTitle sets the "source_base_title" field.
func (_c *NocoDBRestoreCreate) SetSourceBaseTitle(v string) *NocoDBRestoreCreate {
	_c.mutation.SetSourceBaseTitle(v)
	return _c
}

// SetNillableSourceBaseTitle sets the "source_base_title" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableSourceBaseTitle(v *string) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetSourceBaseTitle(*v)
	}
	return _c
}

// SetTargetConnectionID sets the "target_connection_id" field.
func (_c *NocoDBRestoreCreate) SetTargetConnectionID(v string) *NocoDBRestoreCreate {
	_c.mutation.SetTargetConnectionID(v)
	return _c
}

// SetTargetBaseID sets the "target_base_id" field.
func (_c *NocoDBRestoreCreate) SetTargetBaseID(v string) *NocoDBRestoreCreate {
	_c.mutation.SetTargetBaseID(v)
	return _c
}

// SetNillableTargetBaseID sets the "target_base_id" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableTargetBaseID(v *string) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetTargetBaseID(*v)
	}
	return _c
}

// SetTargetBaseTitle sets the "target_base_title" field.
func (_c *NocoDBRestoreCreate) SetTargetBaseTitle(v string) *NocoDBRestoreCreate {
	_c.mutation.SetTargetBaseTitle(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *NocoDBRestoreCreate) SetStatus(v string) *NocoDBRestoreCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetError sets the "error" field.
func (_c *NocoDBRestoreCreate) SetError(v string) *NocoDBRestoreCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableError(v *string) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *NocoDBRestoreCreate) SetProgress(v string) *NocoDBRestoreCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableProgress(v *string) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetTableCount sets the "table_count" field.
func (_c *NocoDBRestoreCreate) SetTableCount(v int) *NocoDBRestoreCreate {
	_c.mutation.SetTableCount(v)
	return _c
}

// SetNillableTableCount sets the "table_count" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableTableCount(v *int) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetTableCount(*v)
	}
	return _c
}

// SetRecordCount sets the "record_count" field.
func (_c *NocoDBRestoreCreate) SetRecordCount(v int64) *NocoDBRestoreCreate {
	_c.mutation.SetRecordCount(v)
	return _c
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableRecordCount(v *int64) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetRecordCount(*v)
	}
	return _c
}

// SetLinkCount sets the "link_count" field.
func (_c *NocoDBRestoreCreate) SetLinkCount(v int64) *NocoDBRestoreCreate {
	_c.mutation.SetLinkCount(v)
	return _c
}

// SetNillableLinkCount sets the "link_count" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableLinkCount(v *int64) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetLinkCount(*v)
	}
	return _c
}

// SetFileCount sets the "file_count" field.
func (_c *NocoDBRestoreCreate) SetFileCount(v int64) *NocoDBRestoreCreate {
	_c.mutation.SetFileCount(v)
	return _c
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableFileCount(v *int64) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetFileCount(*v)
	}
	return _c
}

// SetWarnings sets the "warnings" field.
func (_c *NocoDBRestoreCreate) SetWarnings(v []nocodb.RestoreWarning) *NocoDBRestoreCreate {
	_c.mutation.SetWarnings(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NocoDBRestoreCreate) SetCreatedAt(v time.Time) *NocoDBRestoreCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *NocoDBRestoreCreate) SetStartedAt(v time.Time) *NocoDBRestoreCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableStartedAt(v *time.Time) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *NocoDBRestoreCreate) SetFinishedAt(v time.Time) *NocoDBRestoreCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *NocoDBRestoreCreate) SetNillableFinishedAt(v *time.Time) *NocoDBRestoreCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NocoDBRestoreCreate) SetID(v string) *NocoDBRestoreCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NocoDBRestoreMutation object of the builder.
func (_c *NocoDBRestoreCreate) Mutation() *NocoDBRestoreMutation {
	return _c.mutation
}

// Save creates the NocoDBRestore in the database.
func (_c *NocoDBRestoreCreate) Save(ctx context.Context) (*NocoDBRestore, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NocoDBRestoreCreate) SaveX(ctx context.Context) *NocoDBRestore {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NocoDBRestoreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NocoDBRestoreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NocoDBRestoreCreate) defaults() {
	if _, ok := _c.mutation.SourceBaseTitle(); !ok {
		v := nocodbrestore.DefaultSourceBaseTitle
		_c.mutation.SetSourceBaseTitle(v)
	}
	if _, ok := _c.mutation.TargetBaseID(); !ok {
		v := nocodbrestore.DefaultTargetBaseID
		_c.mutation.SetTargetBaseID(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := nocodbrestore.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := nocodbrestore.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.TableCount(); !ok {
		v := nocodbrestore.DefaultTableCount
		_c.mutation.SetTableCount(v)
	}
	if _, ok := _c.mutation.RecordCount(); !ok {
		v := nocodbrestore.DefaultRecordCount
		_c.mutation.SetRecordCount(v)
	}
	if _, ok := _c.mutation.LinkCount(); !ok {
		v := nocodbrestore.DefaultLinkCount
		_c.mutation.SetLinkCount(v)
	}
	if _, ok := _c.mutation.FileCount(); !ok {
		v := nocodbrestore.DefaultFileCount
		_c.mutation.SetFileCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NocoDBRestoreCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NocoDBRestore.user_id"`)}
	}
	if _, ok := _c.mutation.SnapshotID(); !ok {
		return &ValidationError{Name: "snapshot_id", err: errors.New(`ent: missing required field "NocoDBRestore.snapshot_id"`)}
	}
	if _, ok := _c.mutation.SourceConnectionID(); !ok {
		return &ValidationError{Name: "source_connection_id", err: errors.New(`ent: missing required field "NocoDBRestore.source_connection_id"`)}
	}
	if _, ok := _c.mutation.SourceBaseID(); !ok {
		return &ValidationError{Name: "source_base_id", err: errors.New(`ent: missing required field "NocoDBRestore.source_base_id"`)}
	}
	if _, ok := _c.mutation.SourceBaseTitle(); !ok {
		return &ValidationError{Name: "source_base_title", err: errors.New(`ent: missing required field "NocoDBRestore.source_base_title"`)}
	}
	if _, ok := _c.mutation.TargetConnectionID(); !ok {
		return &ValidationError{Name: "target_connection_id", err: errors.New(`ent: missing required field "NocoDBRestore.target_connection_id"`)}
	}
	if _, ok := _c.mutation.TargetBaseID(); !ok {
		return &ValidationError{Name: "target_base_id", err: errors.New(`ent: missing required field "NocoDBRestore.target_base_id"`)}
	}
	if _, ok := _c.mutation.TargetBaseTitle(); !ok {
		return &ValidationError{Name: "target_base_title", err: errors.New(`ent: missing required field "NocoDBRestore.target_base_title"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NocoDBRestore.status"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "NocoDBRestore.error"`)}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "NocoDBRestore.progress"`)}
	}
	if _, ok := _c.mutation.TableCount(); !ok {
		return &ValidationError{Name: "table_count", err: errors.New(`ent: missing required field "NocoDBRestore.table_count"`)}
	}
	if _, ok := _c.mutation.RecordCount(); !ok {
		return &ValidationError{Name: "record_count", err: errors.New(`ent: missing required field "NocoDBRestore.record_count"`)}
	}
	if _, ok := _c.mutation.LinkCount(); !ok {
		return &ValidationError{Name: "link_count", err: errors.New(`ent: missing required field "NocoDBRestore.link_count"`)}
	}
	if _, ok := _c.mutation.FileCount(); !ok {
		return &ValidationError{Name: "file_count", err: errors.New(`ent: missing required field "NocoDBRestore.file_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NocoDBRestore.created_at"`)}
	}
	return nil
}

func (_c *NocoDBRestoreCreate) sqlSave(ctx context.Context) (*NocoDBRestore, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NocoDBRestore.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NocoDBRestoreCreate) createSpec() (*NocoDBRestore, *sqlgraph.CreateSpec) {
	var (
		_node = &NocoDBRestore{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nocodbrestore.Table, sqlgraph.NewFieldSpec(nocodbrestore.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(nocodbrestore.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.SnapshotID(); ok {
		_spec.SetField(nocodbrestore.FieldSnapshotID, field.TypeString, value)
		_node.SnapshotID = value
	}
	if value, ok := _c.mutation.SourceConnectionID(); ok {
		_spec.SetField(nocodbrestore.FieldSourceConnectionID, field.TypeString, value)
		_node.SourceConnectionID = value
	}
	if value, ok := _c.mutation.SourceBaseID(); ok {
		_spec.SetField(nocodbrestore.FieldSourceBaseID, field.TypeString, value)
		_node.SourceBaseID = value
	}
	if value, ok := _c.mutation.SourceBaseTitle(); ok {
		_spec.SetField(nocodbrestore.FieldSourceBaseTitle, field.TypeString, value)
		_node.SourceBaseTitle = value
	}
	if value, ok := _c.mutation.TargetConnectionID(); ok {
		_spec.SetField(nocodbrestore.FieldTargetConnectionID, field.TypeString, value)
		_node.TargetConnectionID = value
	}
	if value, ok := _c.mutation.TargetBaseID(); ok {
		_spec.SetField(nocodbrestore.FieldTargetBaseID, field.TypeString, value)
		_node.TargetBaseID = value
	}
	if value, ok := _c.mutation.TargetBaseTitle(); ok {
		_spec.SetField(nocodbrestore.FieldTargetBaseTitle, field.TypeString, value)
		_node.TargetBaseTitle = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(nocodbrestore.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(nocodbrestore.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(nocodbrestore.FieldProgress, field.TypeString, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.TableCount(); ok {
		_spec.SetField(nocodbrestore.FieldTableCount, field.TypeInt, value)
		_node.TableCount = value
	}
	if value, ok := _c.mutation.RecordCount(); ok {
		_spec.SetField(nocodbrestore.FieldRecordCount, field.TypeInt64, value)
		_node.RecordCount = value
	}
	if value, ok := _c.mutation.LinkCount(); ok {
		_spec.SetField(nocodbrestore.FieldLinkCount, field.TypeInt64, value)
		_node.LinkCount = value
	}
	if value, ok := _c.mutation.FileCount(); ok {
		_spec.SetField(nocodbrestore.FieldFileCount, field.TypeInt64, value)
		_node.FileCount = value
	}
	if value, ok := _c.mutation.Warnings(); ok {
		_spec.SetField(nocodbrestore.FieldWarnings, field.TypeJSON, value)
		_node.Warnings = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(nocodbrestore.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(nocodbrestore.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(nocodbrestore.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NocoDBRestore.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NocoDBRestoreUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *NocoDBRestoreCreate) OnConflict(opts ...sql.ConflictOption) *NocoDBRestoreUpsertOne {
	_c.conflict = opts
	return &NocoDBRestoreUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NocoDBRestore.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NocoDBRestoreCreate) OnConflictColumns(columns ...string) *NocoDBRestoreUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NocoDBRestoreUpsertOne{
		create: _c,
	}
}

type (
	// NocoDBRestoreUpsertOne is the builder for "upsert"-ing
	//  one NocoDBRestore node.
	NocoDBRestoreUpsertOne struct {
		create *NocoDBRestoreCreate
	}

	// NocoDBRestoreUpsert is the "OnConflict" setter.
	NocoDBRestoreUpsert struct {
		*sql.UpdateSet
	}
)

// SetTargetBaseID sets the "target_base_id" field.
func (u *NocoDBRestoreUpsert) SetTargetBaseID(v string) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldTargetBaseID, v)
	return u
}

// UpdateTargetBaseID sets the "target_base_id" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateTargetBaseID() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldTargetBaseID)
	return u
}

// SetStatus sets the "status" field.
func (u *NocoDBRestoreUpsert) SetStatus(v string) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateStatus() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldStatus)
	return u
}

// SetError sets the "error" field.
func (u *NocoDBRestoreUpsert) SetError(v string) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateError() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldError)
	return u
}

// SetProgress sets the "progress" field.
func (u *NocoDBRestoreUpsert) SetProgress(v string) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldProgress, v)
	return u
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateProgress() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldProgress)
	return u
}

// SetTableCount sets the "table_count" field.
func (u *NocoDBRestoreUpsert) SetTableCount(v int) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldTableCount, v)
	return u
}

// UpdateTableCount sets the "table_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateTableCount() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldTableCount)
	return u
}

// AddTableCount adds v to the "table_count" field.
func (u *NocoDBRestoreUpsert) AddTableCount(v int) *NocoDBRestoreUpsert {
	u.Add(nocodbrestore.FieldTableCount, v)
	return u
}

// SetRecordCount sets the "record_count" field.
func (u *NocoDBRestoreUpsert) SetRecordCount(v int64) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldRecordCount, v)
	return u
}

// UpdateRecordCount sets the "record_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateRecordCount() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldRecordCount)
	return u
}

// AddRecordCount adds v to the "record_count" field.
func (u *NocoDBRestoreUpsert) AddRecordCount(v int64) *NocoDBRestoreUpsert {
	u.Add(nocodbrestore.FieldRecordCount, v)
	return u
}

// SetLinkCount sets the "link_count" field.
func (u *NocoDBRestoreUpsert) SetLinkCount(v int64) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldLinkCount, v)
	return u
}

// UpdateLinkCount sets the "link_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateLinkCount() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldLinkCount)
	return u
}

// AddLinkCount adds v to the "link_count" field.
func (u *NocoDBRestoreUpsert) AddLinkCount(v int64) *NocoDBRestoreUpsert {
	u.Add(nocodbrestore.FieldLinkCount, v)
	return u
}

// SetFileCount sets the "file_count" field.
func (u *NocoDBRestoreUpsert) SetFileCount(v int64) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldFileCount, v)
	return u
}

// UpdateFileCount sets the "file_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateFileCount() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldFileCount)
	return u
}

// AddFileCount adds v to the "file_count" field.
func (u *NocoDBRestoreUpsert) AddFileCount(v int64) *NocoDBRestoreUpsert {
	u.Add(nocodbrestore.FieldFileCount, v)
	return u
}

// SetWarnings sets the "warnings" field.
func (u *NocoDBRestoreUpsert) SetWarnings(v []nocodb.RestoreWarning) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldWarnings, v)
	return u
}

// UpdateWarnings sets the "warnings" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateWarnings() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldWarnings)
	return u
}

// ClearWarnings clears the value of the "warnings" field.
func (u *NocoDBRestoreUpsert) ClearWarnings() *NocoDBRestoreUpsert {
	u.SetNull(nocodbrestore.FieldWarnings)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *NocoDBRestoreUpsert) SetStartedAt(v time.Time) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateStartedAt() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *NocoDBRestoreUpsert) ClearStartedAt() *NocoDBRestoreUpsert {
	u.SetNull(nocodbrestore.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *NocoDBRestoreUpsert) SetFinishedAt(v time.Time) *NocoDBRestoreUpsert {
	u.Set(nocodbrestore.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *NocoDBRestoreUpsert) UpdateFinishedAt() *NocoDBRestoreUpsert {
	u.SetExcluded(nocodbrestore.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *NocoDBRestoreUpsert) ClearFinishedAt() *NocoDBRestoreUpsert {
	u.SetNull(nocodbrestore.FieldFinishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NocoDBRestore.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(nocodbrestore.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NocoDBRestoreUpsertOne) UpdateNewValues() *NocoDBRestoreUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(nocodbrestore.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(nocodbrestore.FieldUserID)
		}
		if _, exists := u.create.mutation.SnapshotID(); exists {
			s.SetIgnore(nocodbrestore.FieldSnapshotID)
		}
		if _, exists := u.create.mutation.SourceConnectionID(); exists {
			s.SetIgnore(nocodbrestore.FieldSourceConnectionID)
		}
		if _, exists := u.create.mutation.SourceBaseID(); exists {
			s.SetIgnore(nocodbrestore.FieldSourceBaseID)
		}
		if _, exists := u.create.mutation.SourceBaseTitle(); exists {
			s.SetIgnore(nocodbrestore.FieldSourceBaseTitle)
		}
		if _, exists := u.create.mutation.TargetConnectionID(); exists {
			s.SetIgnore(nocodbrestore.FieldTargetConnectionID)
		}
		if _, exists := u.create.mutation.TargetBaseTitle(); exists {
			s.SetIgnore(nocodbrestore.FieldTargetBaseTitle)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(nocodbrestore.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NocoDBRestore.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NocoDBRestoreUpsertOne) Ignore() *NocoDBRestoreUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NocoDBRestoreUpsertOne) DoNothing() *NocoDBRestoreUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NocoDBRestoreCreate.OnConflict
// documentation for more info.
func (u *NocoDBRestoreUpsertOne) Update(set func(*NocoDBRestoreUpsert)) *NocoDBRestoreUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NocoDBRestoreUpsert{UpdateSet: update})
	}))
	return u
}

// SetTargetBaseID sets the "target_base_id" field.
func (u *NocoDBRestoreUpsertOne) SetTargetBaseID(v string) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetTargetBaseID(v)
	})
}

// UpdateTargetBaseID sets the "target_base_id" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateTargetBaseID() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateTargetBaseID()
	})
}

// SetStatus sets the "status" field.
func (u *NocoDBRestoreUpsertOne) SetStatus(v string) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateStatus() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *NocoDBRestoreUpsertOne) SetError(v string) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateError() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateError()
	})
}

// SetProgress sets the "progress" field.
func (u *NocoDBRestoreUpsertOne) SetProgress(v string) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateProgress() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateProgress()
	})
}

// SetTableCount sets the "table_count" field.
func (u *NocoDBRestoreUpsertOne) SetTableCount(v int) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetTableCount(v)
	})
}

// AddTableCount adds v to the "table_count" field.
func (u *NocoDBRestoreUpsertOne) AddTableCount(v int) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.AddTableCount(v)
	})
}

// UpdateTableCount sets the "table_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateTableCount() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateTableCount()
	})
}

// SetRecordCount sets the "record_count" field.
func (u *NocoDBRestoreUpsertOne) SetRecordCount(v int64) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetRecordCount(v)
	})
}

// AddRecordCount adds v to the "record_count" field.
func (u *NocoDBRestoreUpsertOne) AddRecordCount(v int64) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.AddRecordCount(v)
	})
}

// UpdateRecordCount sets the "record_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateRecordCount() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateRecordCount()
	})
}

// SetLinkCount sets the "link_count" field.
func (u *NocoDBRestoreUpsertOne) SetLinkCount(v int64) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetLinkCount(v)
	})
}

// AddLinkCount adds v to the "link_count" field.
func (u *NocoDBRestoreUpsertOne) AddLinkCount(v int64) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.AddLinkCount(v)
	})
}

// UpdateLinkCount sets the "link_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateLinkCount() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateLinkCount()
	})
}

// SetFileCount sets the "file_count" field.
func (u *NocoDBRestoreUpsertOne) SetFileCount(v int64) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetFileCount(v)
	})
}

// AddFileCount adds v to the "file_count" field.
func (u *NocoDBRestoreUpsertOne) AddFileCount(v int64) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.AddFileCount(v)
	})
}

// UpdateFileCount sets the "file_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateFileCount() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateFileCount()
	})
}

// SetWarnings sets the "warnings" field.
func (u *NocoDBRestoreUpsertOne) SetWarnings(v []nocodb.RestoreWarning) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetWarnings(v)
	})
}

// UpdateWarnings sets the "warnings" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateWarnings() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateWarnings()
	})
}

// ClearWarnings clears the value of the "warnings" field.
func (u *NocoDBRestoreUpsertOne) ClearWarnings() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.ClearWarnings()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *NocoDBRestoreUpsertOne) SetStartedAt(v time.Time) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateStartedAt() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *NocoDBRestoreUpsertOne) ClearStartedAt() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *NocoDBRestoreUpsertOne) SetFinishedAt(v time.Time) *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertOne) UpdateFinishedAt() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *NocoDBRestoreUpsertOne) ClearFinishedAt() *NocoDBRestoreUpsertOne {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *NocoDBRestoreUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NocoDBRestoreCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NocoDBRestoreUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NocoDBRestoreUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NocoDBRestoreUpsertOne.ID is not supported by MySQL driver. Use NocoDBRestoreUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NocoDBRestoreUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NocoDBRestoreCreateBulk is the builder for creating many NocoDBRestore entities in bulk.
type NocoDBRestoreCreateBulk struct {
	config
	err      error
	builders []*NocoDBRestoreCreate
	conflict []sql.ConflictOption
}

// Save creates the NocoDBRestore entities in the database.
func (_c *NocoDBRestoreCreateBulk) Save(ctx context.Context) ([]*NocoDBRestore, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NocoDBRestore, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NocoDBRestoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NocoDBRestoreCreateBulk) SaveX(ctx context.Context) []*NocoDBRestore {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NocoDBRestoreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NocoDBRestoreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NocoDBRestore.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NocoDBRestoreUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *NocoDBRestoreCreateBulk) OnConflict(opts ...sql.ConflictOption) *NocoDBRestoreUpsertBulk {
	_c.conflict = opts
	return &NocoDBRestoreUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NocoDBRestore.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NocoDBRestoreCreateBulk) OnConflictColumns(columns ...string) *NocoDBRestoreUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NocoDBRestoreUpsertBulk{
		create: _c,
	}
}

// NocoDBRestoreUpsertBulk is the builder for "upsert"-ing
// a bulk of NocoDBRestore nodes.
type NocoDBRestoreUpsertBulk struct {
	create *NocoDBRestoreCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NocoDBRestore.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(nocodbrestore.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NocoDBRestoreUpsertBulk) UpdateNewValues() *NocoDBRestoreUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(nocodbrestore.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(nocodbrestore.FieldUserID)
			}
			if _, exists := b.mutation.SnapshotID(); exists {
				s.SetIgnore(nocodbrestore.FieldSnapshotID)
			}
			if _, exists := b.mutation.SourceConnectionID(); exists {
				s.SetIgnore(nocodbrestore.FieldSourceConnectionID)
			}
			if _, exists := b.mutation.SourceBaseID(); exists {
				s.SetIgnore(nocodbrestore.FieldSourceBaseID)
			}
			if _, exists := b.mutation.SourceBaseTitle(); exists {
				s.SetIgnore(nocodbrestore.FieldSourceBaseTitle)
			}
			if _, exists := b.mutation.TargetConnectionID(); exists {
				s.SetIgnore(nocodbrestore.FieldTargetConnectionID)
			}
			if _, exists := b.mutation.TargetBaseTitle(); exists {
				s.SetIgnore(nocodbrestore.FieldTargetBaseTitle)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(nocodbrestore.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NocoDBRestore.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NocoDBRestoreUpsertBulk) Ignore() *NocoDBRestoreUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NocoDBRestoreUpsertBulk) DoNothing() *NocoDBRestoreUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NocoDBRestoreCreateBulk.OnConflict
// documentation for more info.
func (u *NocoDBRestoreUpsertBulk) Update(set func(*NocoDBRestoreUpsert)) *NocoDBRestoreUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NocoDBRestoreUpsert{UpdateSet: update})
	}))
	return u
}

// SetTargetBaseID sets the "target_base_id" field.
func (u *NocoDBRestoreUpsertBulk) SetTargetBaseID(v string) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetTargetBaseID(v)
	})
}

// UpdateTargetBaseID sets the "target_base_id" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateTargetBaseID() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateTargetBaseID()
	})
}

// SetStatus sets the "status" field.
func (u *NocoDBRestoreUpsertBulk) SetStatus(v string) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateStatus() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *NocoDBRestoreUpsertBulk) SetError(v string) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateError() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateError()
	})
}

// SetProgress sets the "progress" field.
func (u *NocoDBRestoreUpsertBulk) SetProgress(v string) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateProgress() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateProgress()
	})
}

// SetTableCount sets the "table_count" field.
func (u *NocoDBRestoreUpsertBulk) SetTableCount(v int) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetTableCount(v)
	})
}

// AddTableCount adds v to the "table_count" field.
func (u *NocoDBRestoreUpsertBulk) AddTableCount(v int) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.AddTableCount(v)
	})
}

// UpdateTableCount sets the "table_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateTableCount() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateTableCount()
	})
}

// SetRecordCount sets the "record_count" field.
func (u *NocoDBRestoreUpsertBulk) SetRecordCount(v int64) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetRecordCount(v)
	})
}

// AddRecordCount adds v to the "record_count" field.
func (u *NocoDBRestoreUpsertBulk) AddRecordCount(v int64) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.AddRecordCount(v)
	})
}

// UpdateRecordCount sets the "record_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateRecordCount() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateRecordCount()
	})
}

// SetLinkCount sets the "link_count" field.
func (u *NocoDBRestoreUpsertBulk) SetLinkCount(v int64) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetLinkCount(v)
	})
}

// AddLinkCount adds v to the "link_count" field.
func (u *NocoDBRestoreUpsertBulk) AddLinkCount(v int64) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.AddLinkCount(v)
	})
}

// UpdateLinkCount sets the "link_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateLinkCount() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateLinkCount()
	})
}

// SetFileCount sets the "file_count" field.
func (u *NocoDBRestoreUpsertBulk) SetFileCount(v int64) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetFileCount(v)
	})
}

// AddFileCount adds v to the "file_count" field.
func (u *NocoDBRestoreUpsertBulk) AddFileCount(v int64) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.AddFileCount(v)
	})
}

// UpdateFileCount sets the "file_count" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateFileCount() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateFileCount()
	})
}

// SetWarnings sets the "warnings" field.
func (u *NocoDBRestoreUpsertBulk) SetWarnings(v []nocodb.RestoreWarning) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetWarnings(v)
	})
}

// UpdateWarnings sets the "warnings" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateWarnings() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateWarnings()
	})
}

// ClearWarnings clears the value of the "warnings" field.
func (u *NocoDBRestoreUpsertBulk) ClearWarnings() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.ClearWarnings()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *NocoDBRestoreUpsertBulk) SetStartedAt(v time.Time) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateStartedAt() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *NocoDBRestoreUpsertBulk) ClearStartedAt() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *NocoDBRestoreUpsertBulk) SetFinishedAt(v time.Time) *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *NocoDBRestoreUpsertBulk) UpdateFinishedAt() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *NocoDBRestoreUpsertBulk) ClearFinishedAt() *NocoDBRestoreUpsertBulk {
	return u.Update(func(s *NocoDBRestoreUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *NocoDBRestoreUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NocoDBRestoreCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NocoDBRestoreCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NocoDBRestoreUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
