// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"go.orx.me/apps/neo-box/internal/ent/notificationchannel"
)

// NotificationChannel is the model entity for the NotificationChannel schema.
type NotificationChannel struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Config holds the value of the "config" field.
	Config string `json:"config,omitempty"`
	// SecretCiphertext holds the value of the "secret_ciphertext" field.
	SecretCiphertext string `json:"-"`
	// LastSentAt holds the value of the "last_sent_at" field.
	LastSentAt *time.Time `json:"last_sent_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationchannel.FieldEnabled:
			values[i] = new(sql.NullBool)
		case notificationchannel.FieldID, notificationchannel.FieldUserID, notificationchannel.FieldType, notificationchannel.FieldName, notificationchannel.FieldConfig, notificationchannel.FieldSecretCiphertext, notificationchannel.FieldLastError:
			values[i] = new(sql.NullString)
		case notificationchannel.FieldLastSentAt, notificationchannel.FieldCreatedAt, notificationchannel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationChannel fields.
func (_m *NotificationChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationchannel.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case notificationchannel.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case notificationchannel.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case notificationchannel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case notificationchannel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case notificationchannel.FieldConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value.Valid {
				_m.Config = value.String
			}
		case notificationchannel.FieldSecretCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_ciphertext", values[i])
			} else if value.Valid {
				_m.SecretCiphertext = value.String
			}
		case notificationchannel.FieldLastSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sent_at", values[i])
			} else if value.Valid {
				_m.LastSentAt = new(time.Time)
				*_m.LastSentAt = value.Time
			}
		case notificationchannel.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case notificationchannel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case notificationchannel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationChannel.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationChannel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationChannel.
// Note that you need to call NotificationChannel.Unwrap() before calling this method if this NotificationChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationChannel) Update() *NotificationChannelUpdateOne {
	return NewNotificationChannelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationChannel) Unwrap() *NotificationChannel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationChannel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationChannel) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationChannel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(_m.Config)
	builder.WriteString(", ")
	builder.WriteString("secret_ciphertext=<sensitive>")
	builder.WriteString(", ")
	if v := _m.LastSentAt; v != nil {
		builder.WriteString("last_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationChannels is a parsable slice of NotificationChannel.
type NotificationChannels []*NotificationChannel
