// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/notificationchannel"
	"go.orx.me/apps/neo-box/internal/ent/predicate"
)

// NotificationChannelUpdate is the builder for updating NotificationChannel entities.
type NotificationChannelUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationChannelMutation
}

// Where appends a list predicates to the NotificationChannelUpdate builder.
func (_u *NotificationChannelUpdate) Where(ps ...predicate.NotificationChannel) *NotificationChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NotificationChannelUpdate) SetName(v string) *NotificationChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableName(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationChannelUpdate) SetEnabled(v bool) *NotificationChannelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableEnabled(v *bool) *NotificationChannelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *NotificationChannelUpdate) SetConfig(v string) *NotificationChannelUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableConfig(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetSecretCiphertext sets the "secret_ciphertext" field.
func (_u *NotificationChannelUpdate) SetSecretCiphertext(v string) *NotificationChannelUpdate {
	_u.mutation.SetSecretCiphertext(v)
	return _u
}

// SetNillableSecretCiphertext sets the "secret_ciphertext" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableSecretCiphertext(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetSecretCiphertext(*v)
	}
	return _u
}

// SetLastSentAt sets the "last_sent_at" field.
func (_u *NotificationChannelUpdate) SetLastSentAt(v time.Time) *NotificationChannelUpdate {
	_u.mutation.SetLastSentAt(v)
	return _u
}

// SetNillableLastSentAt sets the "last_sent_at" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableLastSentAt(v *time.Time) *NotificationChannelUpdate {
	if v != nil {
		_u.SetLastSentAt(*v)
	}
	return _u
}

// ClearLastSentAt clears the value of the "last_sent_at" field.
func (_u *NotificationChannelUpdate) ClearLastSentAt() *NotificationChannelUpdate {
	_u.mutation.ClearLastSentAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *NotificationChannelUpdate) SetLastError(v string) *NotificationChannelUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableLastError(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationChannelUpdate) SetUpdatedAt(v time.Time) *NotificationChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableUpdatedAt(v *time.Time) *NotificationChannelUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_u *NotificationChannelUpdate) Mutation() *NotificationChannelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationChannelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NotificationChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationchannel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(notificationchannel.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretCiphertext(); ok {
		_spec.SetField(notificationchannel.FieldSecretCiphertext, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSentAt(); ok {
		_spec.SetField(notificationchannel.FieldLastSentAt, field.TypeTime, value)
	}
	if _u.mutation.LastSentAtCleared() {
		_spec.ClearField(notificationchannel.FieldLastSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(notificationchannel.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationChannelUpdateOne is the builder for updating a single NotificationChannel entity.
type NotificationChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationChannelMutation
}

// SetName sets the "name" field.
func (_u *NotificationChannelUpdateOne) SetName(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableName(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationChannelUpdateOne) SetEnabled(v bool) *NotificationChannelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableEnabled(v *bool) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *NotificationChannelUpdateOne) SetConfig(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableConfig(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetSecretCiphertext sets the "secret_ciphertext" field.
func (_u *NotificationChannelUpdateOne) SetSecretCiphertext(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetSecretCiphertext(v)
	return _u
}

// SetNillableSecretCiphertext sets the "secret_ciphertext" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableSecretCiphertext(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetSecretCiphertext(*v)
	}
	return _u
}

// SetLastSentAt sets the "last_sent_at" field.
func (_u *NotificationChannelUpdateOne) SetLastSentAt(v time.Time) *NotificationChannelUpdateOne {
	_u.mutation.SetLastSentAt(v)
	return _u
}

// SetNillableLastSentAt sets the "last_sent_at" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableLastSentAt(v *time.Time) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetLastSentAt(*v)
	}
	return _u
}

// ClearLastSentAt clears the value of the "last_sent_at" field.
func (_u *NotificationChannelUpdateOne) ClearLastSentAt() *NotificationChannelUpdateOne {
	_u.mutation.ClearLastSentAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *NotificationChannelUpdateOne) SetLastError(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableLastError(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationChannelUpdateOne) SetUpdatedAt(v time.Time) *NotificationChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableUpdatedAt(v *time.Time) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_u *NotificationChannelUpdateOne) Mutation() *NotificationChannelMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationChannelUpdate builder.
func (_u *NotificationChannelUpdateOne) Where(ps ...predicate.NotificationChannel) *NotificationChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationChannelUpdateOne) Select(field string, fields ...string) *NotificationChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationChannel entity.
func (_u *NotificationChannelUpdateOne) Save(ctx context.Context) (*NotificationChannel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelUpdateOne) SaveX(ctx context.Context) *NotificationChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NotificationChannelUpdateOne) sqlSave(ctx context.Context) (_node *NotificationChannel, err error) {
	_spec := sqlgraph.NewUpdateSpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationchannel.FieldID)
		for _, f := range fields {
			if !notificationchannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationchannel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(notificationchannel.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretCiphertext(); ok {
		_spec.SetField(notificationchannel.FieldSecretCiphertext, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSentAt(); ok {
		_spec.SetField(notificationchannel.FieldLastSentAt, field.TypeTime, value)
	}
	if _u.mutation.LastSentAtCleared() {
		_spec.ClearField(notificationchannel.FieldLastSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(notificationchannel.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &NotificationChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
