// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"go.orx.me/apps/neo-box/internal/ent/oauthstate"
)

// OAuthStateCreate is the builder for creating a OAuthState entity.
type OAuthStateCreate struct {
	config
	mutation *OAuthStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (_c *OAuthStateCreate) SetProvider(v string) *OAuthStateCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthStateCreate) SetRedirectURI(v string) *OAuthStateCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_c *OAuthStateCreate) SetNillableRedirectURI(v *string) *OAuthStateCreate {
	if v != nil {
		_c.SetRedirectURI(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthStateCreate) SetCreatedAt(v time.Time) *OAuthStateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthStateCreate) SetExpiresAt(v time.Time) *OAuthStateCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthStateCreate) SetID(v string) *OAuthStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OAuthStateMutation object of the builder.
func (_c *OAuthStateCreate) Mutation() *OAuthStateMutation {
	return _c.mutation
}

// Save creates the OAuthState in the database.
func (_c *OAuthStateCreate) Save(ctx context.Context) (*OAuthState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthStateCreate) SaveX(ctx context.Context) *OAuthState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthStateCreate) defaults() {
	if _, ok := _c.mutation.RedirectURI(); !ok {
		v := oauthstate.DefaultRedirectURI
		_c.mutation.SetRedirectURI(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthStateCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "OAuthState.provider"`)}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OAuthState.redirect_uri"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthState.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthState.expires_at"`)}
	}
	return nil
}

func (_c *OAuthStateCreate) sqlSave(ctx context.Context) (*OAuthState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OAuthState.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthStateCreate) createSpec() (*OAuthState, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthstate.Table, sqlgraph.NewFieldSpec(oauthstate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(oauthstate.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthstate.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthstate.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthState.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthStateUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthStateCreate) OnConflict(opts ...sql.ConflictOption) *OAuthStateUpsertOne {
	_c.conflict = opts
	return &OAuthStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthStateCreate) OnConflictColumns(columns ...string) *OAuthStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthStateUpsertOne{
		create: _c,
	}
}

type (
	// OAuthStateUpsertOne is the builder for "upsert"-ing
	//  one OAuthState node.
	OAuthStateUpsertOne struct {
		create *OAuthStateCreate
	}

	// OAuthStateUpsert is the "OnConflict" setter.
	OAuthStateUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OAuthState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauthstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuthStateUpsertOne) UpdateNewValues() *OAuthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(oauthstate.FieldID)
		}
		if _, exists := u.create.mutation.Provider(); exists {
			s.SetIgnore(oauthstate.FieldProvider)
		}
		if _, exists := u.create.mutation.RedirectURI(); exists {
			s.SetIgnore(oauthstate.FieldRedirectURI)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthstate.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ExpiresAt(); exists {
			s.SetIgnore(oauthstate.FieldExpiresAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthStateUpsertOne) Ignore() *OAuthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthStateUpsertOne) DoNothing() *OAuthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthStateCreate.OnConflict
// documentation for more info.
func (u *OAuthStateUpsertOne) Update(set func(*OAuthStateUpsert)) *OAuthStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthStateUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *OAuthStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthStateUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OAuthStateUpsertOne.ID is not supported by MySQL driver. Use OAuthStateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthStateUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthStateCreateBulk is the builder for creating many OAuthState entities in bulk.
type OAuthStateCreateBulk struct {
	config
	err      error
	builders []*OAuthStateCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthState entities in the database.
func (_c *OAuthStateCreateBulk) Save(ctx context.Context) ([]*OAuthState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthStateCreateBulk) SaveX(ctx context.Context) []*OAuthState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthStateUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthStateUpsertBulk {
	_c.conflict = opts
	return &OAuthStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthStateCreateBulk) OnConflictColumns(columns ...string) *OAuthStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthStateUpsertBulk{
		create: _c,
	}
}

// OAuthStateUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthState nodes.
type OAuthStateUpsertBulk struct {
	create *OAuthStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauthstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuthStateUpsertBulk) UpdateNewValues() *OAuthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(oauthstate.FieldID)
			}
			if _, exists := b.mutation.Provider(); exists {
				s.SetIgnore(oauthstate.FieldProvider)
			}
			if _, exists := b.mutation.RedirectURI(); exists {
				s.SetIgnore(oauthstate.FieldRedirectURI)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthstate.FieldCreatedAt)
			}
			if _, exists := b.mutation.ExpiresAt(); exists {
				s.SetIgnore(oauthstate.FieldExpiresAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthStateUpsertBulk) Ignore() *OAuthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthStateUpsertBulk) DoNothing() *OAuthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthStateCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthStateUpsertBulk) Update(set func(*OAuthStateUpsert)) *OAuthStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthStateUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *OAuthStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
