// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go.orx.me/apps/neo-box/internal/ent/alert"
	"go.orx.me/apps/neo-box/internal/ent/connection"
	"go.orx.me/apps/neo-box/internal/ent/nocodbbackuppolicy"
	"go.orx.me/apps/neo-box/internal/ent/nocodbrestore"
	"go.orx.me/apps/neo-box/internal/ent/nocodbsnapshot"
	"go.orx.me/apps/neo-box/internal/ent/notificationchannel"
	"go.orx.me/apps/neo-box/internal/ent/oauthstate"
	"go.orx.me/apps/neo-box/internal/ent/schema"
	"go.orx.me/apps/neo-box/internal/ent/session"
	"go.orx.me/apps/neo-box/internal/ent/user"
	"go.orx.me/apps/neo-box/internal/ent/wasabidailyusage"
	"go.orx.me/apps/neo-box/internal/ent/wasabisyncstate"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alertFields := schema.Alert{}.Fields()
	_ = alertFields
	// alertDescConnectionID is the schema descriptor for connection_id field.
	alertDescConnectionID := alertFields[3].Descriptor()
	// alert.DefaultConnectionID holds the default value on creation for the connection_id field.
	alert.DefaultConnectionID = alertDescConnectionID.Default.(string)
	// alertDescBody is the schema descriptor for body field.
	alertDescBody := alertFields[8].Descriptor()
	// alert.DefaultBody holds the default value on creation for the body field.
	alert.DefaultBody = alertDescBody.Default.(string)
	// alertDescLink is the schema descriptor for link field.
	alertDescLink := alertFields[9].Descriptor()
	// alert.DefaultLink holds the default value on creation for the link field.
	alert.DefaultLink = alertDescLink.Default.(string)
	// alertDescDeliveryError is the schema descriptor for delivery_error field.
	alertDescDeliveryError := alertFields[12].Descriptor()
	// alert.DefaultDeliveryError holds the default value on creation for the delivery_error field.
	alert.DefaultDeliveryError = alertDescDeliveryError.Default.(string)
	connectionFields := schema.Connection{}.Fields()
	_ = connectionFields
	// connectionDescStatus is the schema descriptor for status field.
	connectionDescStatus := connectionFields[6].Descriptor()
	// connection.DefaultStatus holds the default value on creation for the status field.
	connection.DefaultStatus = connectionDescStatus.Default.(string)
	// connectionDescStatusMessage is the schema descriptor for status_message field.
	connectionDescStatusMessage := connectionFields[7].Descriptor()
	// connection.DefaultStatusMessage holds the default value on creation for the status_message field.
	connection.DefaultStatusMessage = connectionDescStatusMessage.Default.(string)
	nocodbbackuppolicyFields := schema.NocoDBBackupPolicy{}.Fields()
	_ = nocodbbackuppolicyFields
	// nocodbbackuppolicyDescIncludeAttachments is the schema descriptor for include_attachments field.
	nocodbbackuppolicyDescIncludeAttachments := nocodbbackuppolicyFields[6].Descriptor()
	// nocodbbackuppolicy.DefaultIncludeAttachments holds the default value on creation for the include_attachments field.
	nocodbbackuppolicy.DefaultIncludeAttachments = nocodbbackuppolicyDescIncludeAttachments.Default.(bool)
	nocodbrestoreFields := schema.NocoDBRestore{}.Fields()
	_ = nocodbrestoreFields
	// nocodbrestoreDescSourceBaseTitle is the schema descriptor for source_base_title field.
	nocodbrestoreDescSourceBaseTitle := nocodbrestoreFields[5].Descriptor()
	// nocodbrestore.DefaultSourceBaseTitle holds the default value on creation for the source_base_title field.
	nocodbrestore.DefaultSourceBaseTitle = nocodbrestoreDescSourceBaseTitle.Default.(string)
	// nocodbrestoreDescTargetBaseID is the schema descriptor for target_base_id field.
	nocodbrestoreDescTargetBaseID := nocodbrestoreFields[7].Descriptor()
	// nocodbrestore.DefaultTargetBaseID holds the default value on creation for the target_base_id field.
	nocodbrestore.DefaultTargetBaseID = nocodbrestoreDescTargetBaseID.Default.(string)
	// nocodbrestoreDescError is the schema descriptor for error field.
	nocodbrestoreDescError := nocodbrestoreFields[10].Descriptor()
	// nocodbrestore.DefaultError holds the default value on creation for the error field.
	nocodbrestore.DefaultError = nocodbrestoreDescError.Default.(string)
	// nocodbrestoreDescProgress is the schema descriptor for progress field.
	nocodbrestoreDescProgress := nocodbrestoreFields[11].Descriptor()
	// nocodbrestore.DefaultProgress holds the default value on creation for the progress field.
	nocodbrestore.DefaultProgress = nocodbrestoreDescProgress.Default.(string)
	// nocodbrestoreDescTableCount is the schema descriptor for table_count field.
	nocodbrestoreDescTableCount := nocodbrestoreFields[12].Descriptor()
	// nocodbrestore.DefaultTableCount holds the default value on creation for the table_count field.
	nocodbrestore.DefaultTableCount = nocodbrestoreDescTableCount.Default.(int)
	// nocodbrestoreDescRecordCount is the schema descriptor for record_count field.
	nocodbrestoreDescRecordCount := nocodbrestoreFields[13].Descriptor()
	// nocodbrestore.DefaultRecordCount holds the default value on creation for the record_count field.
	nocodbrestore.DefaultRecordCount = nocodbrestoreDescRecordCount.Default.(int64)
	// nocodbrestoreDescLinkCount is the schema descriptor for link_count field.
	nocodbrestoreDescLinkCount := nocodbrestoreFields[14].Descriptor()
	// nocodbrestore.DefaultLinkCount holds the default value on creation for the link_count field.
	nocodbrestore.DefaultLinkCount = nocodbrestoreDescLinkCount.Default.(int64)
	// nocodbrestoreDescFileCount is the schema descriptor for file_count field.
	nocodbrestoreDescFileCount := nocodbrestoreFields[15].Descriptor()
	// nocodbrestore.DefaultFileCount holds the default value on creation for the file_count field.
	nocodbrestore.DefaultFileCount = nocodbrestoreDescFileCount.Default.(int64)
	// nocodbrestoreDescViewCount is the schema descriptor for view_count field.
	nocodbrestoreDescViewCount := nocodbrestoreFields[16].Descriptor()
	// nocodbrestore.DefaultViewCount holds the default value on creation for the view_count field.
	nocodbrestore.DefaultViewCount = nocodbrestoreDescViewCount.Default.(int)
	nocodbsnapshotFields := schema.NocoDBSnapshot{}.Fields()
	_ = nocodbsnapshotFields
	// nocodbsnapshotDescBaseTitle is the schema descriptor for base_title field.
	nocodbsnapshotDescBaseTitle := nocodbsnapshotFields[4].Descriptor()
	// nocodbsnapshot.DefaultBaseTitle holds the default value on creation for the base_title field.
	nocodbsnapshot.DefaultBaseTitle = nocodbsnapshotDescBaseTitle.Default.(string)
	// nocodbsnapshotDescError is the schema descriptor for error field.
	nocodbsnapshotDescError := nocodbsnapshotFields[7].Descriptor()
	// nocodbsnapshot.DefaultError holds the default value on creation for the error field.
	nocodbsnapshot.DefaultError = nocodbsnapshotDescError.Default.(string)
	// nocodbsnapshotDescProgress is the schema descriptor for progress field.
	nocodbsnapshotDescProgress := nocodbsnapshotFields[8].Descriptor()
	// nocodbsnapshot.DefaultProgress holds the default value on creation for the progress field.
	nocodbsnapshot.DefaultProgress = nocodbsnapshotDescProgress.Default.(string)
	// nocodbsnapshotDescObjectKey is the schema descriptor for object_key field.
	nocodbsnapshotDescObjectKey := nocodbsnapshotFields[9].Descriptor()
	// nocodbsnapshot.DefaultObjectKey holds the default value on creation for the object_key field.
	nocodbsnapshot.DefaultObjectKey = nocodbsnapshotDescObjectKey.Default.(string)
	// nocodbsnapshotDescSizeBytes is the schema descriptor for size_bytes field.
	nocodbsnapshotDescSizeBytes := nocodbsnapshotFields[10].Descriptor()
	// nocodbsnapshot.DefaultSizeBytes holds the default value on creation for the size_bytes field.
	nocodbsnapshot.DefaultSizeBytes = nocodbsnapshotDescSizeBytes.Default.(int64)
	// nocodbsnapshotDescRecordCount is the schema descriptor for record_count field.
	nocodbsnapshotDescRecordCount := nocodbsnapshotFields[11].Descriptor()
	// nocodbsnapshot.DefaultRecordCount holds the default value on creation for the record_count field.
	nocodbsnapshot.DefaultRecordCount = nocodbsnapshotDescRecordCount.Default.(int64)
	// nocodbsnapshotDescLinkCount is the schema descriptor for link_count field.
	nocodbsnapshotDescLinkCount := nocodbsnapshotFields[12].Descriptor()
	// nocodbsnapshot.DefaultLinkCount holds the default value on creation for the link_count field.
	nocodbsnapshot.DefaultLinkCount = nocodbsnapshotDescLinkCount.Default.(int64)
	// nocodbsnapshotDescViewCount is the schema descriptor for view_count field.
	nocodbsnapshotDescViewCount := nocodbsnapshotFields[13].Descriptor()
	// nocodbsnapshot.DefaultViewCount holds the default value on creation for the view_count field.
	nocodbsnapshot.DefaultViewCount = nocodbsnapshotDescViewCount.Default.(int)
	// nocodbsnapshotDescAttachmentsIncluded is the schema descriptor for attachments_included field.
	nocodbsnapshotDescAttachmentsIncluded := nocodbsnapshotFields[14].Descriptor()
	// nocodbsnapshot.DefaultAttachmentsIncluded holds the default value on creation for the attachments_included field.
	nocodbsnapshot.DefaultAttachmentsIncluded = nocodbsnapshotDescAttachmentsIncluded.Default.(bool)
	// nocodbsnapshotDescFileCount is the schema descriptor for file_count field.
	nocodbsnapshotDescFileCount := nocodbsnapshotFields[15].Descriptor()
	// nocodbsnapshot.DefaultFileCount holds the default value on creation for the file_count field.
	nocodbsnapshot.DefaultFileCount = nocodbsnapshotDescFileCount.Default.(int64)
	// nocodbsnapshotDescFileBytes is the schema descriptor for file_bytes field.
	nocodbsnapshotDescFileBytes := nocodbsnapshotFields[16].Descriptor()
	// nocodbsnapshot.DefaultFileBytes holds the default value on creation for the file_bytes field.
	nocodbsnapshot.DefaultFileBytes = nocodbsnapshotDescFileBytes.Default.(int64)
	// nocodbsnapshotDescFilesMissing is the schema descriptor for files_missing field.
	nocodbsnapshotDescFilesMissing := nocodbsnapshotFields[17].Descriptor()
	// nocodbsnapshot.DefaultFilesMissing holds the default value on creation for the files_missing field.
	nocodbsnapshot.DefaultFilesMissing = nocodbsnapshotDescFilesMissing.Default.(int64)
	notificationchannelFields := schema.NotificationChannel{}.Fields()
	_ = notificationchannelFields
	// notificationchannelDescEnabled is the schema descriptor for enabled field.
	notificationchannelDescEnabled := notificationchannelFields[4].Descriptor()
	// notificationchannel.DefaultEnabled holds the default value on creation for the enabled field.
	notificationchannel.DefaultEnabled = notificationchannelDescEnabled.Default.(bool)
	// notificationchannelDescLastError is the schema descriptor for last_error field.
	notificationchannelDescLastError := notificationchannelFields[8].Descriptor()
	// notificationchannel.DefaultLastError holds the default value on creation for the last_error field.
	notificationchannel.DefaultLastError = notificationchannelDescLastError.Default.(string)
	oauthstateFields := schema.OAuthState{}.Fields()
	_ = oauthstateFields
	// oauthstateDescRedirectURI is the schema descriptor for redirect_uri field.
	oauthstateDescRedirectURI := oauthstateFields[2].Descriptor()
	// oauthstate.DefaultRedirectURI holds the default value on creation for the redirect_uri field.
	oauthstate.DefaultRedirectURI = oauthstateDescRedirectURI.Default.(string)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescRevoked is the schema descriptor for revoked field.
	sessionDescRevoked := sessionFields[6].Descriptor()
	// session.DefaultRevoked holds the default value on creation for the revoked field.
	session.DefaultRevoked = sessionDescRevoked.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[2].Descriptor()
	// user.DefaultDisplayName holds the default value on creation for the display_name field.
	user.DefaultDisplayName = userDescDisplayName.Default.(string)
	// userDescAvatarURL is the schema descriptor for avatar_url field.
	userDescAvatarURL := userFields[3].Descriptor()
	// user.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	user.DefaultAvatarURL = userDescAvatarURL.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescProvider is the schema descriptor for provider field.
	userDescProvider := userFields[5].Descriptor()
	// user.DefaultProvider holds the default value on creation for the provider field.
	user.DefaultProvider = userDescProvider.Default.(string)
	// userDescExternalID is the schema descriptor for external_id field.
	userDescExternalID := userFields[6].Descriptor()
	// user.DefaultExternalID holds the default value on creation for the external_id field.
	user.DefaultExternalID = userDescExternalID.Default.(string)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[7].Descriptor()
	// user.DefaultPasswordHash holds the default value on creation for the password_hash field.
	user.DefaultPasswordHash = userDescPasswordHash.Default.(string)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[8].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[9].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	wasabidailyusageFields := schema.WasabiDailyUsage{}.Fields()
	_ = wasabidailyusageFields
	// wasabidailyusageDescBucket is the schema descriptor for bucket field.
	wasabidailyusageDescBucket := wasabidailyusageFields[1].Descriptor()
	// wasabidailyusage.DefaultBucket holds the default value on creation for the bucket field.
	wasabidailyusage.DefaultBucket = wasabidailyusageDescBucket.Default.(string)
	// wasabidailyusageDescRegion is the schema descriptor for region field.
	wasabidailyusageDescRegion := wasabidailyusageFields[3].Descriptor()
	// wasabidailyusage.DefaultRegion holds the default value on creation for the region field.
	wasabidailyusage.DefaultRegion = wasabidailyusageDescRegion.Default.(string)
	// wasabidailyusageDescNumBillableObjects is the schema descriptor for num_billable_objects field.
	wasabidailyusageDescNumBillableObjects := wasabidailyusageFields[4].Descriptor()
	// wasabidailyusage.DefaultNumBillableObjects holds the default value on creation for the num_billable_objects field.
	wasabidailyusage.DefaultNumBillableObjects = wasabidailyusageDescNumBillableObjects.Default.(int64)
	// wasabidailyusageDescNumBillableDeletedObjects is the schema descriptor for num_billable_deleted_objects field.
	wasabidailyusageDescNumBillableDeletedObjects := wasabidailyusageFields[5].Descriptor()
	// wasabidailyusage.DefaultNumBillableDeletedObjects holds the default value on creation for the num_billable_deleted_objects field.
	wasabidailyusage.DefaultNumBillableDeletedObjects = wasabidailyusageDescNumBillableDeletedObjects.Default.(int64)
	// wasabidailyusageDescRawStorageSizeBytes is the schema descriptor for raw_storage_size_bytes field.
	wasabidailyusageDescRawStorageSizeBytes := wasabidailyusageFields[6].Descriptor()
	// wasabidailyusage.DefaultRawStorageSizeBytes holds the default value on creation for the raw_storage_size_bytes field.
	wasabidailyusage.DefaultRawStorageSizeBytes = wasabidailyusageDescRawStorageSizeBytes.Default.(int64)
	// wasabidailyusageDescPaddedStorageSizeBytes is the schema descriptor for padded_storage_size_bytes field.
	wasabidailyusageDescPaddedStorageSizeBytes := wasabidailyusageFields[7].Descriptor()
	// wasabidailyusage.DefaultPaddedStorageSizeBytes holds the default value on creation for the padded_storage_size_bytes field.
	wasabidailyusage.DefaultPaddedStorageSizeBytes = wasabidailyusageDescPaddedStorageSizeBytes.Default.(int64)
	// wasabidailyusageDescMetadataStorageSizeBytes is the schema descriptor for metadata_storage_size_bytes field.
	wasabidailyusageDescMetadataStorageSizeBytes := wasabidailyusageFields[8].Descriptor()
	// wasabidailyusage.DefaultMetadataStorageSizeBytes holds the default value on creation for the metadata_storage_size_bytes field.
	wasabidailyusage.DefaultMetadataStorageSizeBytes = wasabidailyusageDescMetadataStorageSizeBytes.Default.(int64)
	// wasabidailyusageDescDeletedStorageSizeBytes is the schema descriptor for deleted_storage_size_bytes field.
	wasabidailyusageDescDeletedStorageSizeBytes := wasabidailyusageFields[9].Descriptor()
	// wasabidailyusage.DefaultDeletedStorageSizeBytes holds the default value on creation for the deleted_storage_size_bytes field.
	wasabidailyusage.DefaultDeletedStorageSizeBytes = wasabidailyusageDescDeletedStorageSizeBytes.Default.(int64)
	// wasabidailyusageDescOrphanedStorageSizeBytes is the schema descriptor for orphaned_storage_size_bytes field.
	wasabidailyusageDescOrphanedStorageSizeBytes := wasabidailyusageFields[10].Descriptor()
	// wasabidailyusage.DefaultOrphanedStorageSizeBytes holds the default value on creation for the orphaned_storage_size_bytes field.
	wasabidailyusage.DefaultOrphanedStorageSizeBytes = wasabidailyusageDescOrphanedStorageSizeBytes.Default.(int64)
	// wasabidailyusageDescMinStorageChargeBytes is the schema descriptor for min_storage_charge_bytes field.
	wasabidailyusageDescMinStorageChargeBytes := wasabidailyusageFields[11].Descriptor()
	// wasabidailyusage.DefaultMinStorageChargeBytes holds the default value on creation for the min_storage_charge_bytes field.
	wasabidailyusage.DefaultMinStorageChargeBytes = wasabidailyusageDescMinStorageChargeBytes.Default.(int64)
	// wasabidailyusageDescNumAPICalls is the schema descriptor for num_api_calls field.
	wasabidailyusageDescNumAPICalls := wasabidailyusageFields[12].Descriptor()
	// wasabidailyusage.DefaultNumAPICalls holds the default value on creation for the num_api_calls field.
	wasabidailyusage.DefaultNumAPICalls = wasabidailyusageDescNumAPICalls.Default.(int64)
	// wasabidailyusageDescUploadBytes is the schema descriptor for upload_bytes field.
	wasabidailyusageDescUploadBytes := wasabidailyusageFields[13].Descriptor()
	// wasabidailyusage.DefaultUploadBytes holds the default value on creation for the upload_bytes field.
	wasabidailyusage.DefaultUploadBytes = wasabidailyusageDescUploadBytes.Default.(int64)
	// wasabidailyusageDescDownloadBytes is the schema descriptor for download_bytes field.
	wasabidailyusageDescDownloadBytes := wasabidailyusageFields[14].Descriptor()
	// wasabidailyusage.DefaultDownloadBytes holds the default value on creation for the download_bytes field.
	wasabidailyusage.DefaultDownloadBytes = wasabidailyusageDescDownloadBytes.Default.(int64)
	// wasabidailyusageDescStorageWroteBytes is the schema descriptor for storage_wrote_bytes field.
	wasabidailyusageDescStorageWroteBytes := wasabidailyusageFields[15].Descriptor()
	// wasabidailyusage.DefaultStorageWroteBytes holds the default value on creation for the storage_wrote_bytes field.
	wasabidailyusage.DefaultStorageWroteBytes = wasabidailyusageDescStorageWroteBytes.Default.(int64)
	// wasabidailyusageDescStorageReadBytes is the schema descriptor for storage_read_bytes field.
	wasabidailyusageDescStorageReadBytes := wasabidailyusageFields[16].Descriptor()
	// wasabidailyusage.DefaultStorageReadBytes holds the default value on creation for the storage_read_bytes field.
	wasabidailyusage.DefaultStorageReadBytes = wasabidailyusageDescStorageReadBytes.Default.(int64)
	// wasabidailyusageDescDeleteBytes is the schema descriptor for delete_bytes field.
	wasabidailyusageDescDeleteBytes := wasabidailyusageFields[17].Descriptor()
	// wasabidailyusage.DefaultDeleteBytes holds the default value on creation for the delete_bytes field.
	wasabidailyusage.DefaultDeleteBytes = wasabidailyusageDescDeleteBytes.Default.(int64)
	// wasabidailyusageDescNumGetCalls is the schema descriptor for num_get_calls field.
	wasabidailyusageDescNumGetCalls := wasabidailyusageFields[18].Descriptor()
	// wasabidailyusage.DefaultNumGetCalls holds the default value on creation for the num_get_calls field.
	wasabidailyusage.DefaultNumGetCalls = wasabidailyusageDescNumGetCalls.Default.(int64)
	// wasabidailyusageDescNumPutCalls is the schema descriptor for num_put_calls field.
	wasabidailyusageDescNumPutCalls := wasabidailyusageFields[19].Descriptor()
	// wasabidailyusage.DefaultNumPutCalls holds the default value on creation for the num_put_calls field.
	wasabidailyusage.DefaultNumPutCalls = wasabidailyusageDescNumPutCalls.Default.(int64)
	// wasabidailyusageDescNumDeleteCalls is the schema descriptor for num_delete_calls field.
	wasabidailyusageDescNumDeleteCalls := wasabidailyusageFields[20].Descriptor()
	// wasabidailyusage.DefaultNumDeleteCalls holds the default value on creation for the num_delete_calls field.
	wasabidailyusage.DefaultNumDeleteCalls = wasabidailyusageDescNumDeleteCalls.Default.(int64)
	// wasabidailyusageDescNumListCalls is the schema descriptor for num_list_calls field.
	wasabidailyusageDescNumListCalls := wasabidailyusageFields[21].Descriptor()
	// wasabidailyusage.DefaultNumListCalls holds the default value on creation for the num_list_calls field.
	wasabidailyusage.DefaultNumListCalls = wasabidailyusageDescNumListCalls.Default.(int64)
	// wasabidailyusageDescNumHeadCalls is the schema descriptor for num_head_calls field.
	wasabidailyusageDescNumHeadCalls := wasabidailyusageFields[22].Descriptor()
	// wasabidailyusage.DefaultNumHeadCalls holds the default value on creation for the num_head_calls field.
	wasabidailyusage.DefaultNumHeadCalls = wasabidailyusageDescNumHeadCalls.Default.(int64)
	wasabisyncstateFields := schema.WasabiSyncState{}.Fields()
	_ = wasabisyncstateFields
	// wasabisyncstateDescConfigError is the schema descriptor for config_error field.
	wasabisyncstateDescConfigError := wasabisyncstateFields[7].Descriptor()
	// wasabisyncstate.DefaultConfigError holds the default value on creation for the config_error field.
	wasabisyncstate.DefaultConfigError = wasabisyncstateDescConfigError.Default.(string)
}
