// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go.orx.me/apps/neo-box/internal/ent/nocodbsnapshot"
	"go.orx.me/apps/neo-box/internal/ent/oauthstate"
	"go.orx.me/apps/neo-box/internal/ent/schema"
	"go.orx.me/apps/neo-box/internal/ent/session"
	"go.orx.me/apps/neo-box/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	nocodbsnapshotFields := schema.NocoDBSnapshot{}.Fields()
	_ = nocodbsnapshotFields
	// nocodbsnapshotDescBaseTitle is the schema descriptor for base_title field.
	nocodbsnapshotDescBaseTitle := nocodbsnapshotFields[4].Descriptor()
	// nocodbsnapshot.DefaultBaseTitle holds the default value on creation for the base_title field.
	nocodbsnapshot.DefaultBaseTitle = nocodbsnapshotDescBaseTitle.Default.(string)
	// nocodbsnapshotDescError is the schema descriptor for error field.
	nocodbsnapshotDescError := nocodbsnapshotFields[7].Descriptor()
	// nocodbsnapshot.DefaultError holds the default value on creation for the error field.
	nocodbsnapshot.DefaultError = nocodbsnapshotDescError.Default.(string)
	// nocodbsnapshotDescProgress is the schema descriptor for progress field.
	nocodbsnapshotDescProgress := nocodbsnapshotFields[8].Descriptor()
	// nocodbsnapshot.DefaultProgress holds the default value on creation for the progress field.
	nocodbsnapshot.DefaultProgress = nocodbsnapshotDescProgress.Default.(string)
	// nocodbsnapshotDescObjectKey is the schema descriptor for object_key field.
	nocodbsnapshotDescObjectKey := nocodbsnapshotFields[9].Descriptor()
	// nocodbsnapshot.DefaultObjectKey holds the default value on creation for the object_key field.
	nocodbsnapshot.DefaultObjectKey = nocodbsnapshotDescObjectKey.Default.(string)
	// nocodbsnapshotDescSizeBytes is the schema descriptor for size_bytes field.
	nocodbsnapshotDescSizeBytes := nocodbsnapshotFields[10].Descriptor()
	// nocodbsnapshot.DefaultSizeBytes holds the default value on creation for the size_bytes field.
	nocodbsnapshot.DefaultSizeBytes = nocodbsnapshotDescSizeBytes.Default.(int64)
	// nocodbsnapshotDescRecordCount is the schema descriptor for record_count field.
	nocodbsnapshotDescRecordCount := nocodbsnapshotFields[11].Descriptor()
	// nocodbsnapshot.DefaultRecordCount holds the default value on creation for the record_count field.
	nocodbsnapshot.DefaultRecordCount = nocodbsnapshotDescRecordCount.Default.(int64)
	// nocodbsnapshotDescLinkCount is the schema descriptor for link_count field.
	nocodbsnapshotDescLinkCount := nocodbsnapshotFields[12].Descriptor()
	// nocodbsnapshot.DefaultLinkCount holds the default value on creation for the link_count field.
	nocodbsnapshot.DefaultLinkCount = nocodbsnapshotDescLinkCount.Default.(int64)
	oauthstateFields := schema.OAuthState{}.Fields()
	_ = oauthstateFields
	// oauthstateDescRedirectURI is the schema descriptor for redirect_uri field.
	oauthstateDescRedirectURI := oauthstateFields[2].Descriptor()
	// oauthstate.DefaultRedirectURI holds the default value on creation for the redirect_uri field.
	oauthstate.DefaultRedirectURI = oauthstateDescRedirectURI.Default.(string)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescRevoked is the schema descriptor for revoked field.
	sessionDescRevoked := sessionFields[6].Descriptor()
	// session.DefaultRevoked holds the default value on creation for the revoked field.
	session.DefaultRevoked = sessionDescRevoked.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[2].Descriptor()
	// user.DefaultDisplayName holds the default value on creation for the display_name field.
	user.DefaultDisplayName = userDescDisplayName.Default.(string)
	// userDescAvatarURL is the schema descriptor for avatar_url field.
	userDescAvatarURL := userFields[3].Descriptor()
	// user.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	user.DefaultAvatarURL = userDescAvatarURL.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescProvider is the schema descriptor for provider field.
	userDescProvider := userFields[5].Descriptor()
	// user.DefaultProvider holds the default value on creation for the provider field.
	user.DefaultProvider = userDescProvider.Default.(string)
	// userDescExternalID is the schema descriptor for external_id field.
	userDescExternalID := userFields[6].Descriptor()
	// user.DefaultExternalID holds the default value on creation for the external_id field.
	user.DefaultExternalID = userDescExternalID.Default.(string)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[7].Descriptor()
	// user.DefaultPasswordHash holds the default value on creation for the password_hash field.
	user.DefaultPasswordHash = userDescPasswordHash.Default.(string)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[8].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[9].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
}
