// Code generated by ent, DO NOT EDIT.

package nocodbsnapshotfile

import (
	"entgo.io/ent/dialect/sql"
	"go.orx.me/apps/neo-box/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldLTE(FieldID, id))
}

// SnapshotID applies equality check predicate on the "snapshot_id" field. It's identical to SnapshotIDEQ.
func SnapshotID(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEQ(FieldSnapshotID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEQ(FieldUserID, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEQ(FieldSha256, v))
}

// SnapshotIDEQ applies the EQ predicate on the "snapshot_id" field.
func SnapshotIDEQ(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEQ(FieldSnapshotID, v))
}

// SnapshotIDNEQ applies the NEQ predicate on the "snapshot_id" field.
func SnapshotIDNEQ(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldNEQ(FieldSnapshotID, v))
}

// SnapshotIDIn applies the In predicate on the "snapshot_id" field.
func SnapshotIDIn(vs ...string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldIn(FieldSnapshotID, vs...))
}

// SnapshotIDNotIn applies the NotIn predicate on the "snapshot_id" field.
func SnapshotIDNotIn(vs ...string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldNotIn(FieldSnapshotID, vs...))
}

// SnapshotIDGT applies the GT predicate on the "snapshot_id" field.
func SnapshotIDGT(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldGT(FieldSnapshotID, v))
}

// SnapshotIDGTE applies the GTE predicate on the "snapshot_id" field.
func SnapshotIDGTE(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldGTE(FieldSnapshotID, v))
}

// SnapshotIDLT applies the LT predicate on the "snapshot_id" field.
func SnapshotIDLT(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldLT(FieldSnapshotID, v))
}

// SnapshotIDLTE applies the LTE predicate on the "snapshot_id" field.
func SnapshotIDLTE(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldLTE(FieldSnapshotID, v))
}

// SnapshotIDContains applies the Contains predicate on the "snapshot_id" field.
func SnapshotIDContains(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldContains(FieldSnapshotID, v))
}

// SnapshotIDHasPrefix applies the HasPrefix predicate on the "snapshot_id" field.
func SnapshotIDHasPrefix(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldHasPrefix(FieldSnapshotID, v))
}

// SnapshotIDHasSuffix applies the HasSuffix predicate on the "snapshot_id" field.
func SnapshotIDHasSuffix(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldHasSuffix(FieldSnapshotID, v))
}

// SnapshotIDEqualFold applies the EqualFold predicate on the "snapshot_id" field.
func SnapshotIDEqualFold(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEqualFold(FieldSnapshotID, v))
}

// SnapshotIDContainsFold applies the ContainsFold predicate on the "snapshot_id" field.
func SnapshotIDContainsFold(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldContainsFold(FieldSnapshotID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldContainsFold(FieldUserID, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.FieldContainsFold(FieldSha256, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NocoDBSnapshotFile) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NocoDBSnapshotFile) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NocoDBSnapshotFile) predicate.NocoDBSnapshotFile {
	return predicate.NocoDBSnapshotFile(sql.NotPredicates(p))
}
