// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: neobox/v1/nocodb.proto

package neoboxv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BackupPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BackupPolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BackupPolicy with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BackupPolicyMultiError, or
// nil if none found.
func (m *BackupPolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *BackupPolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConnectionId

	// no validation rules for BaseId

	// no validation rules for Enabled

	// no validation rules for Cron

	// no validation rules for Retention

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BackupPolicyValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BackupPolicyValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BackupPolicyValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetNextRunAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BackupPolicyValidationError{
					field:  "NextRunAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BackupPolicyValidationError{
					field:  "NextRunAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNextRunAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BackupPolicyValidationError{
				field:  "NextRunAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BackupPolicyMultiError(errors)
	}

	return nil
}

// BackupPolicyMultiError is an error wrapping multiple validation errors
// returned by BackupPolicy.ValidateAll() if the designated constraints aren't met.
type BackupPolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BackupPolicyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BackupPolicyMultiError) AllErrors() []error { return m }

// BackupPolicyValidationError is the validation error returned by
// BackupPolicy.Validate if the designated constraints aren't met.
type BackupPolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BackupPolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BackupPolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BackupPolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BackupPolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BackupPolicyValidationError) ErrorName() string { return "BackupPolicyValidationError" }

// Error satisfies the builtin error interface
func (e BackupPolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBackupPolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BackupPolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BackupPolicyValidationError{}

// Validate checks the field values on NocoDBBase with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NocoDBBase) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NocoDBBase with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NocoDBBaseMultiError, or
// nil if none found.
func (m *NocoDBBase) ValidateAll() error {
	return m.validate(true)
}

func (m *NocoDBBase) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	if all {
		switch v := interface{}(m.GetPolicy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NocoDBBaseValidationError{
					field:  "Policy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NocoDBBaseValidationError{
					field:  "Policy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPolicy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NocoDBBaseValidationError{
				field:  "Policy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLatestSnapshot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NocoDBBaseValidationError{
					field:  "LatestSnapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NocoDBBaseValidationError{
					field:  "LatestSnapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLatestSnapshot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NocoDBBaseValidationError{
				field:  "LatestSnapshot",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return NocoDBBaseMultiError(errors)
	}

	return nil
}

// NocoDBBaseMultiError is an error wrapping multiple validation errors
// returned by NocoDBBase.ValidateAll() if the designated constraints aren't met.
type NocoDBBaseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NocoDBBaseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NocoDBBaseMultiError) AllErrors() []error { return m }

// NocoDBBaseValidationError is the validation error returned by
// NocoDBBase.Validate if the designated constraints aren't met.
type NocoDBBaseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NocoDBBaseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NocoDBBaseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NocoDBBaseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NocoDBBaseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NocoDBBaseValidationError) ErrorName() string { return "NocoDBBaseValidationError" }

// Error satisfies the builtin error interface
func (e NocoDBBaseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNocoDBBase.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NocoDBBaseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NocoDBBaseValidationError{}

// Validate checks the field values on ListNocoDBBasesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListNocoDBBasesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListNocoDBBasesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListNocoDBBasesRequestMultiError, or nil if none found.
func (m *ListNocoDBBasesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListNocoDBBasesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetConnectionId()) < 1 {
		err := ListNocoDBBasesRequestValidationError{
			field:  "ConnectionId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListNocoDBBasesRequestMultiError(errors)
	}

	return nil
}

// ListNocoDBBasesRequestMultiError is an error wrapping multiple validation
// errors returned by ListNocoDBBasesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListNocoDBBasesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListNocoDBBasesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListNocoDBBasesRequestMultiError) AllErrors() []error { return m }

// ListNocoDBBasesRequestValidationError is the validation error returned by
// ListNocoDBBasesRequest.Validate if the designated constraints aren't met.
type ListNocoDBBasesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListNocoDBBasesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListNocoDBBasesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListNocoDBBasesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListNocoDBBasesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListNocoDBBasesRequestValidationError) ErrorName() string {
	return "ListNocoDBBasesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListNocoDBBasesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListNocoDBBasesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListNocoDBBasesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListNocoDBBasesRequestValidationError{}

// Validate checks the field values on ListNocoDBBasesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListNocoDBBasesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListNocoDBBasesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListNocoDBBasesResponseMultiError, or nil if none found.
func (m *ListNocoDBBasesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListNocoDBBasesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBases() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListNocoDBBasesResponseValidationError{
						field:  fmt.Sprintf("Bases[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListNocoDBBasesResponseValidationError{
						field:  fmt.Sprintf("Bases[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListNocoDBBasesResponseValidationError{
					field:  fmt.Sprintf("Bases[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListNocoDBBasesResponseMultiError(errors)
	}

	return nil
}

// ListNocoDBBasesResponseMultiError is an error wrapping multiple validation
// errors returned by ListNocoDBBasesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListNocoDBBasesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListNocoDBBasesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListNocoDBBasesResponseMultiError) AllErrors() []error { return m }

// ListNocoDBBasesResponseValidationError is the validation error returned by
// ListNocoDBBasesResponse.Validate if the designated constraints aren't met.
type ListNocoDBBasesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListNocoDBBasesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListNocoDBBasesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListNocoDBBasesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListNocoDBBasesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListNocoDBBasesResponseValidationError) ErrorName() string {
	return "ListNocoDBBasesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListNocoDBBasesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListNocoDBBasesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListNocoDBBasesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListNocoDBBasesResponseValidationError{}

// Validate checks the field values on UpsertBackupPolicyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertBackupPolicyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertBackupPolicyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertBackupPolicyRequestMultiError, or nil if none found.
func (m *UpsertBackupPolicyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertBackupPolicyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetConnectionId()) < 1 {
		err := UpsertBackupPolicyRequestValidationError{
			field:  "ConnectionId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBaseId()) < 1 {
		err := UpsertBackupPolicyRequestValidationError{
			field:  "BaseId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Enabled

	// no validation rules for Cron

	if m.GetRetention() < 0 {
		err := UpsertBackupPolicyRequestValidationError{
			field:  "Retention",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpsertBackupPolicyRequestMultiError(errors)
	}

	return nil
}

// UpsertBackupPolicyRequestMultiError is an error wrapping multiple validation
// errors returned by UpsertBackupPolicyRequest.ValidateAll() if the
// designated constraints aren't met.
type UpsertBackupPolicyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertBackupPolicyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertBackupPolicyRequestMultiError) AllErrors() []error { return m }

// UpsertBackupPolicyRequestValidationError is the validation error returned by
// UpsertBackupPolicyRequest.Validate if the designated constraints aren't met.
type UpsertBackupPolicyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertBackupPolicyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertBackupPolicyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertBackupPolicyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertBackupPolicyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertBackupPolicyRequestValidationError) ErrorName() string {
	return "UpsertBackupPolicyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertBackupPolicyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertBackupPolicyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertBackupPolicyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertBackupPolicyRequestValidationError{}

// Validate checks the field values on UpsertBackupPolicyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertBackupPolicyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertBackupPolicyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertBackupPolicyResponseMultiError, or nil if none found.
func (m *UpsertBackupPolicyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertBackupPolicyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPolicy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertBackupPolicyResponseValidationError{
					field:  "Policy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertBackupPolicyResponseValidationError{
					field:  "Policy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPolicy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertBackupPolicyResponseValidationError{
				field:  "Policy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpsertBackupPolicyResponseMultiError(errors)
	}

	return nil
}

// UpsertBackupPolicyResponseMultiError is an error wrapping multiple
// validation errors returned by UpsertBackupPolicyResponse.ValidateAll() if
// the designated constraints aren't met.
type UpsertBackupPolicyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertBackupPolicyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertBackupPolicyResponseMultiError) AllErrors() []error { return m }

// UpsertBackupPolicyResponseValidationError is the validation error returned
// by UpsertBackupPolicyResponse.Validate if the designated constraints aren't met.
type UpsertBackupPolicyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertBackupPolicyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertBackupPolicyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertBackupPolicyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertBackupPolicyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertBackupPolicyResponseValidationError) ErrorName() string {
	return "UpsertBackupPolicyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertBackupPolicyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertBackupPolicyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertBackupPolicyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertBackupPolicyResponseValidationError{}

// Validate checks the field values on SnapshotTable with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SnapshotTable) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SnapshotTable with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SnapshotTableMultiError, or
// nil if none found.
func (m *SnapshotTable) ValidateAll() error {
	return m.validate(true)
}

func (m *SnapshotTable) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for RecordCount

	// no validation rules for FieldCount

	// no validation rules for LinkCount

	if len(errors) > 0 {
		return SnapshotTableMultiError(errors)
	}

	return nil
}

// SnapshotTableMultiError is an error wrapping multiple validation errors
// returned by SnapshotTable.ValidateAll() if the designated constraints
// aren't met.
type SnapshotTableMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SnapshotTableMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SnapshotTableMultiError) AllErrors() []error { return m }

// SnapshotTableValidationError is the validation error returned by
// SnapshotTable.Validate if the designated constraints aren't met.
type SnapshotTableValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SnapshotTableValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SnapshotTableValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SnapshotTableValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SnapshotTableValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SnapshotTableValidationError) ErrorName() string { return "SnapshotTableValidationError" }

// Error satisfies the builtin error interface
func (e SnapshotTableValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSnapshotTable.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SnapshotTableValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SnapshotTableValidationError{}

// Validate checks the field values on Snapshot with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Snapshot) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Snapshot with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SnapshotMultiError, or nil
// if none found.
func (m *Snapshot) ValidateAll() error {
	return m.validate(true)
}

func (m *Snapshot) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ConnectionId

	// no validation rules for BaseId

	// no validation rules for BaseTitle

	// no validation rules for Status

	// no validation rules for Trigger

	// no validation rules for Error

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SnapshotValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SnapshotValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SnapshotValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SnapshotValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SnapshotValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SnapshotValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetFinishedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SnapshotValidationError{
					field:  "FinishedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SnapshotValidationError{
					field:  "FinishedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFinishedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SnapshotValidationError{
				field:  "FinishedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SizeBytes

	// no validation rules for RecordCount

	// no validation rules for LinkCount

	for idx, item := range m.GetTables() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SnapshotValidationError{
						field:  fmt.Sprintf("Tables[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SnapshotValidationError{
						field:  fmt.Sprintf("Tables[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SnapshotValidationError{
					field:  fmt.Sprintf("Tables[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Progress

	if len(errors) > 0 {
		return SnapshotMultiError(errors)
	}

	return nil
}

// SnapshotMultiError is an error wrapping multiple validation errors returned
// by Snapshot.ValidateAll() if the designated constraints aren't met.
type SnapshotMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SnapshotMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SnapshotMultiError) AllErrors() []error { return m }

// SnapshotValidationError is the validation error returned by
// Snapshot.Validate if the designated constraints aren't met.
type SnapshotValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SnapshotValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SnapshotValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SnapshotValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SnapshotValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SnapshotValidationError) ErrorName() string { return "SnapshotValidationError" }

// Error satisfies the builtin error interface
func (e SnapshotValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSnapshot.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SnapshotValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SnapshotValidationError{}

// Validate checks the field values on CreateSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSnapshotRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSnapshotRequestMultiError, or nil if none found.
func (m *CreateSnapshotRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSnapshotRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetConnectionId()) < 1 {
		err := CreateSnapshotRequestValidationError{
			field:  "ConnectionId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetBaseId()) < 1 {
		err := CreateSnapshotRequestValidationError{
			field:  "BaseId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateSnapshotRequestMultiError(errors)
	}

	return nil
}

// CreateSnapshotRequestMultiError is an error wrapping multiple validation
// errors returned by CreateSnapshotRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateSnapshotRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSnapshotRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSnapshotRequestMultiError) AllErrors() []error { return m }

// CreateSnapshotRequestValidationError is the validation error returned by
// CreateSnapshotRequest.Validate if the designated constraints aren't met.
type CreateSnapshotRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSnapshotRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSnapshotRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSnapshotRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSnapshotRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSnapshotRequestValidationError) ErrorName() string {
	return "CreateSnapshotRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSnapshotRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSnapshotRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSnapshotRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSnapshotRequestValidationError{}

// Validate checks the field values on CreateSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSnapshotResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSnapshotResponseMultiError, or nil if none found.
func (m *CreateSnapshotResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSnapshotResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSnapshot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateSnapshotResponseValidationError{
					field:  "Snapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateSnapshotResponseValidationError{
					field:  "Snapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSnapshot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateSnapshotResponseValidationError{
				field:  "Snapshot",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateSnapshotResponseMultiError(errors)
	}

	return nil
}

// CreateSnapshotResponseMultiError is an error wrapping multiple validation
// errors returned by CreateSnapshotResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateSnapshotResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSnapshotResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSnapshotResponseMultiError) AllErrors() []error { return m }

// CreateSnapshotResponseValidationError is the validation error returned by
// CreateSnapshotResponse.Validate if the designated constraints aren't met.
type CreateSnapshotResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSnapshotResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSnapshotResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSnapshotResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSnapshotResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSnapshotResponseValidationError) ErrorName() string {
	return "CreateSnapshotResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSnapshotResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSnapshotResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSnapshotResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSnapshotResponseValidationError{}

// Validate checks the field values on ListSnapshotsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSnapshotsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSnapshotsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSnapshotsRequestMultiError, or nil if none found.
func (m *ListSnapshotsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSnapshotsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConnectionId

	// no validation rules for BaseId

	// no validation rules for Limit

	if len(errors) > 0 {
		return ListSnapshotsRequestMultiError(errors)
	}

	return nil
}

// ListSnapshotsRequestMultiError is an error wrapping multiple validation
// errors returned by ListSnapshotsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListSnapshotsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSnapshotsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSnapshotsRequestMultiError) AllErrors() []error { return m }

// ListSnapshotsRequestValidationError is the validation error returned by
// ListSnapshotsRequest.Validate if the designated constraints aren't met.
type ListSnapshotsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSnapshotsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSnapshotsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSnapshotsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSnapshotsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSnapshotsRequestValidationError) ErrorName() string {
	return "ListSnapshotsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListSnapshotsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSnapshotsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSnapshotsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSnapshotsRequestValidationError{}

// Validate checks the field values on ListSnapshotsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSnapshotsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSnapshotsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSnapshotsResponseMultiError, or nil if none found.
func (m *ListSnapshotsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSnapshotsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSnapshots() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListSnapshotsResponseValidationError{
						field:  fmt.Sprintf("Snapshots[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListSnapshotsResponseValidationError{
						field:  fmt.Sprintf("Snapshots[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListSnapshotsResponseValidationError{
					field:  fmt.Sprintf("Snapshots[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListSnapshotsResponseMultiError(errors)
	}

	return nil
}

// ListSnapshotsResponseMultiError is an error wrapping multiple validation
// errors returned by ListSnapshotsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListSnapshotsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSnapshotsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSnapshotsResponseMultiError) AllErrors() []error { return m }

// ListSnapshotsResponseValidationError is the validation error returned by
// ListSnapshotsResponse.Validate if the designated constraints aren't met.
type ListSnapshotsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSnapshotsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSnapshotsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSnapshotsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSnapshotsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSnapshotsResponseValidationError) ErrorName() string {
	return "ListSnapshotsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListSnapshotsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSnapshotsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSnapshotsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSnapshotsResponseValidationError{}

// Validate checks the field values on GetSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSnapshotRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSnapshotRequestMultiError, or nil if none found.
func (m *GetSnapshotRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSnapshotRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetSnapshotRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSnapshotRequestMultiError(errors)
	}

	return nil
}

// GetSnapshotRequestMultiError is an error wrapping multiple validation errors
// returned by GetSnapshotRequest.ValidateAll() if the designated constraints
// aren't met.
type GetSnapshotRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSnapshotRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSnapshotRequestMultiError) AllErrors() []error { return m }

// GetSnapshotRequestValidationError is the validation error returned by
// GetSnapshotRequest.Validate if the designated constraints aren't met.
type GetSnapshotRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSnapshotRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSnapshotRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSnapshotRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSnapshotRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSnapshotRequestValidationError) ErrorName() string {
	return "GetSnapshotRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSnapshotRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSnapshotRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSnapshotRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSnapshotRequestValidationError{}

// Validate checks the field values on GetSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSnapshotResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSnapshotResponseMultiError, or nil if none found.
func (m *GetSnapshotResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSnapshotResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSnapshot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSnapshotResponseValidationError{
					field:  "Snapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSnapshotResponseValidationError{
					field:  "Snapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSnapshot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSnapshotResponseValidationError{
				field:  "Snapshot",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSnapshotResponseMultiError(errors)
	}

	return nil
}

// GetSnapshotResponseMultiError is an error wrapping multiple validation
// errors returned by GetSnapshotResponse.ValidateAll() if the designated
// constraints aren't met.
type GetSnapshotResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSnapshotResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSnapshotResponseMultiError) AllErrors() []error { return m }

// GetSnapshotResponseValidationError is the validation error returned by
// GetSnapshotResponse.Validate if the designated constraints aren't met.
type GetSnapshotResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSnapshotResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSnapshotResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSnapshotResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSnapshotResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSnapshotResponseValidationError) ErrorName() string {
	return "GetSnapshotResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSnapshotResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSnapshotResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSnapshotResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSnapshotResponseValidationError{}

// Validate checks the field values on DeleteSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSnapshotRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteSnapshotRequestMultiError, or nil if none found.
func (m *DeleteSnapshotRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSnapshotRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := DeleteSnapshotRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteSnapshotRequestMultiError(errors)
	}

	return nil
}

// DeleteSnapshotRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteSnapshotRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteSnapshotRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSnapshotRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSnapshotRequestMultiError) AllErrors() []error { return m }

// DeleteSnapshotRequestValidationError is the validation error returned by
// DeleteSnapshotRequest.Validate if the designated constraints aren't met.
type DeleteSnapshotRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSnapshotRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSnapshotRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSnapshotRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSnapshotRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSnapshotRequestValidationError) ErrorName() string {
	return "DeleteSnapshotRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSnapshotRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSnapshotRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSnapshotRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSnapshotRequestValidationError{}

// Validate checks the field values on DeleteSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSnapshotResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteSnapshotResponseMultiError, or nil if none found.
func (m *DeleteSnapshotResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSnapshotResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteSnapshotResponseMultiError(errors)
	}

	return nil
}

// DeleteSnapshotResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteSnapshotResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteSnapshotResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSnapshotResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSnapshotResponseMultiError) AllErrors() []error { return m }

// DeleteSnapshotResponseValidationError is the validation error returned by
// DeleteSnapshotResponse.Validate if the designated constraints aren't met.
type DeleteSnapshotResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSnapshotResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSnapshotResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSnapshotResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSnapshotResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSnapshotResponseValidationError) ErrorName() string {
	return "DeleteSnapshotResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSnapshotResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSnapshotResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSnapshotResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSnapshotResponseValidationError{}

// Validate checks the field values on SnapshotField with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SnapshotField) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SnapshotField with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SnapshotFieldMultiError, or
// nil if none found.
func (m *SnapshotField) ValidateAll() error {
	return m.validate(true)
}

func (m *SnapshotField) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Type

	if len(errors) > 0 {
		return SnapshotFieldMultiError(errors)
	}

	return nil
}

// SnapshotFieldMultiError is an error wrapping multiple validation errors
// returned by SnapshotField.ValidateAll() if the designated constraints
// aren't met.
type SnapshotFieldMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SnapshotFieldMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SnapshotFieldMultiError) AllErrors() []error { return m }

// SnapshotFieldValidationError is the validation error returned by
// SnapshotField.Validate if the designated constraints aren't met.
type SnapshotFieldValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SnapshotFieldValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SnapshotFieldValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SnapshotFieldValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SnapshotFieldValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SnapshotFieldValidationError) ErrorName() string { return "SnapshotFieldValidationError" }

// Error satisfies the builtin error interface
func (e SnapshotFieldValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSnapshotField.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SnapshotFieldValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SnapshotFieldValidationError{}

// Validate checks the field values on ListSnapshotRecordsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSnapshotRecordsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSnapshotRecordsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSnapshotRecordsRequestMultiError, or nil if none found.
func (m *ListSnapshotRecordsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSnapshotRecordsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSnapshotId()) < 1 {
		err := ListSnapshotRecordsRequestValidationError{
			field:  "SnapshotId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTableId()) < 1 {
		err := ListSnapshotRecordsRequestValidationError{
			field:  "TableId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListSnapshotRecordsRequestMultiError(errors)
	}

	return nil
}

// ListSnapshotRecordsRequestMultiError is an error wrapping multiple
// validation errors returned by ListSnapshotRecordsRequest.ValidateAll() if
// the designated constraints aren't met.
type ListSnapshotRecordsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSnapshotRecordsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSnapshotRecordsRequestMultiError) AllErrors() []error { return m }

// ListSnapshotRecordsRequestValidationError is the validation error returned
// by ListSnapshotRecordsRequest.Validate if the designated constraints aren't met.
type ListSnapshotRecordsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSnapshotRecordsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSnapshotRecordsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSnapshotRecordsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSnapshotRecordsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSnapshotRecordsRequestValidationError) ErrorName() string {
	return "ListSnapshotRecordsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListSnapshotRecordsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSnapshotRecordsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSnapshotRecordsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSnapshotRecordsRequestValidationError{}

// Validate checks the field values on ListSnapshotRecordsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSnapshotRecordsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSnapshotRecordsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSnapshotRecordsResponseMultiError, or nil if none found.
func (m *ListSnapshotRecordsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSnapshotRecordsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetFields() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListSnapshotRecordsResponseValidationError{
						field:  fmt.Sprintf("Fields[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListSnapshotRecordsResponseValidationError{
						field:  fmt.Sprintf("Fields[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListSnapshotRecordsResponseValidationError{
					field:  fmt.Sprintf("Fields[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetRecords() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListSnapshotRecordsResponseValidationError{
						field:  fmt.Sprintf("Records[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListSnapshotRecordsResponseValidationError{
						field:  fmt.Sprintf("Records[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListSnapshotRecordsResponseValidationError{
					field:  fmt.Sprintf("Records[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListSnapshotRecordsResponseMultiError(errors)
	}

	return nil
}

// ListSnapshotRecordsResponseMultiError is an error wrapping multiple
// validation errors returned by ListSnapshotRecordsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListSnapshotRecordsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSnapshotRecordsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSnapshotRecordsResponseMultiError) AllErrors() []error { return m }

// ListSnapshotRecordsResponseValidationError is the validation error returned
// by ListSnapshotRecordsResponse.Validate if the designated constraints
// aren't met.
type ListSnapshotRecordsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSnapshotRecordsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSnapshotRecordsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSnapshotRecordsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSnapshotRecordsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSnapshotRecordsResponseValidationError) ErrorName() string {
	return "ListSnapshotRecordsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListSnapshotRecordsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSnapshotRecordsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSnapshotRecordsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSnapshotRecordsResponseValidationError{}
