// Code generated by ent, DO NOT EDIT.

package wasabibucketconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"go.orx.me/apps/neo-box/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLTE(FieldID, id))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldConnectionID, v))
}

// Bucket applies equality check predicate on the "bucket" field. It's identical to BucketEQ.
func Bucket(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldBucket, v))
}

// Config applies equality check predicate on the "config" field. It's identical to ConfigEQ.
func Config(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldConfig, v))
}

// FetchedAt applies equality check predicate on the "fetched_at" field. It's identical to FetchedAtEQ.
func FetchedAt(v time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldFetchedAt, v))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNotIn(FieldConnectionID, vs...))
}

// ConnectionIDGT applies the GT predicate on the "connection_id" field.
func ConnectionIDGT(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGT(FieldConnectionID, v))
}

// ConnectionIDGTE applies the GTE predicate on the "connection_id" field.
func ConnectionIDGTE(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGTE(FieldConnectionID, v))
}

// ConnectionIDLT applies the LT predicate on the "connection_id" field.
func ConnectionIDLT(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLT(FieldConnectionID, v))
}

// ConnectionIDLTE applies the LTE predicate on the "connection_id" field.
func ConnectionIDLTE(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLTE(FieldConnectionID, v))
}

// ConnectionIDContains applies the Contains predicate on the "connection_id" field.
func ConnectionIDContains(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldContains(FieldConnectionID, v))
}

// ConnectionIDHasPrefix applies the HasPrefix predicate on the "connection_id" field.
func ConnectionIDHasPrefix(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldHasPrefix(FieldConnectionID, v))
}

// ConnectionIDHasSuffix applies the HasSuffix predicate on the "connection_id" field.
func ConnectionIDHasSuffix(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldHasSuffix(FieldConnectionID, v))
}

// ConnectionIDEqualFold applies the EqualFold predicate on the "connection_id" field.
func ConnectionIDEqualFold(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEqualFold(FieldConnectionID, v))
}

// ConnectionIDContainsFold applies the ContainsFold predicate on the "connection_id" field.
func ConnectionIDContainsFold(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldContainsFold(FieldConnectionID, v))
}

// BucketEQ applies the EQ predicate on the "bucket" field.
func BucketEQ(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldBucket, v))
}

// BucketNEQ applies the NEQ predicate on the "bucket" field.
func BucketNEQ(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNEQ(FieldBucket, v))
}

// BucketIn applies the In predicate on the "bucket" field.
func BucketIn(vs ...string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldIn(FieldBucket, vs...))
}

// BucketNotIn applies the NotIn predicate on the "bucket" field.
func BucketNotIn(vs ...string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNotIn(FieldBucket, vs...))
}

// BucketGT applies the GT predicate on the "bucket" field.
func BucketGT(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGT(FieldBucket, v))
}

// BucketGTE applies the GTE predicate on the "bucket" field.
func BucketGTE(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGTE(FieldBucket, v))
}

// BucketLT applies the LT predicate on the "bucket" field.
func BucketLT(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLT(FieldBucket, v))
}

// BucketLTE applies the LTE predicate on the "bucket" field.
func BucketLTE(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLTE(FieldBucket, v))
}

// BucketContains applies the Contains predicate on the "bucket" field.
func BucketContains(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldContains(FieldBucket, v))
}

// BucketHasPrefix applies the HasPrefix predicate on the "bucket" field.
func BucketHasPrefix(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldHasPrefix(FieldBucket, v))
}

// BucketHasSuffix applies the HasSuffix predicate on the "bucket" field.
func BucketHasSuffix(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldHasSuffix(FieldBucket, v))
}

// BucketEqualFold applies the EqualFold predicate on the "bucket" field.
func BucketEqualFold(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEqualFold(FieldBucket, v))
}

// BucketContainsFold applies the ContainsFold predicate on the "bucket" field.
func BucketContainsFold(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldContainsFold(FieldBucket, v))
}

// ConfigEQ applies the EQ predicate on the "config" field.
func ConfigEQ(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldConfig, v))
}

// ConfigNEQ applies the NEQ predicate on the "config" field.
func ConfigNEQ(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNEQ(FieldConfig, v))
}

// ConfigIn applies the In predicate on the "config" field.
func ConfigIn(vs ...string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldIn(FieldConfig, vs...))
}

// ConfigNotIn applies the NotIn predicate on the "config" field.
func ConfigNotIn(vs ...string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNotIn(FieldConfig, vs...))
}

// ConfigGT applies the GT predicate on the "config" field.
func ConfigGT(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGT(FieldConfig, v))
}

// ConfigGTE applies the GTE predicate on the "config" field.
func ConfigGTE(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGTE(FieldConfig, v))
}

// ConfigLT applies the LT predicate on the "config" field.
func ConfigLT(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLT(FieldConfig, v))
}

// ConfigLTE applies the LTE predicate on the "config" field.
func ConfigLTE(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLTE(FieldConfig, v))
}

// ConfigContains applies the Contains predicate on the "config" field.
func ConfigContains(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldContains(FieldConfig, v))
}

// ConfigHasPrefix applies the HasPrefix predicate on the "config" field.
func ConfigHasPrefix(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldHasPrefix(FieldConfig, v))
}

// ConfigHasSuffix applies the HasSuffix predicate on the "config" field.
func ConfigHasSuffix(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldHasSuffix(FieldConfig, v))
}

// ConfigEqualFold applies the EqualFold predicate on the "config" field.
func ConfigEqualFold(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEqualFold(FieldConfig, v))
}

// ConfigContainsFold applies the ContainsFold predicate on the "config" field.
func ConfigContainsFold(v string) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldContainsFold(FieldConfig, v))
}

// FetchedAtEQ applies the EQ predicate on the "fetched_at" field.
func FetchedAtEQ(v time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldEQ(FieldFetchedAt, v))
}

// FetchedAtNEQ applies the NEQ predicate on the "fetched_at" field.
func FetchedAtNEQ(v time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNEQ(FieldFetchedAt, v))
}

// FetchedAtIn applies the In predicate on the "fetched_at" field.
func FetchedAtIn(vs ...time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldIn(FieldFetchedAt, vs...))
}

// FetchedAtNotIn applies the NotIn predicate on the "fetched_at" field.
func FetchedAtNotIn(vs ...time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldNotIn(FieldFetchedAt, vs...))
}

// FetchedAtGT applies the GT predicate on the "fetched_at" field.
func FetchedAtGT(v time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGT(FieldFetchedAt, v))
}

// FetchedAtGTE applies the GTE predicate on the "fetched_at" field.
func FetchedAtGTE(v time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldGTE(FieldFetchedAt, v))
}

// FetchedAtLT applies the LT predicate on the "fetched_at" field.
func FetchedAtLT(v time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLT(FieldFetchedAt, v))
}

// FetchedAtLTE applies the LTE predicate on the "fetched_at" field.
func FetchedAtLTE(v time.Time) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.FieldLTE(FieldFetchedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WasabiBucketConfig) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WasabiBucketConfig) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WasabiBucketConfig) predicate.WasabiBucketConfig {
	return predicate.WasabiBucketConfig(sql.NotPredicates(p))
}
