// Code generated by ent, DO NOT EDIT.

package nocodbbackuppolicy

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the nocodbbackuppolicy type in the database.
	Label = "noco_db_backup_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConnectionID holds the string denoting the connection_id field in the database.
	FieldConnectionID = "connection_id"
	// FieldBaseID holds the string denoting the base_id field in the database.
	FieldBaseID = "base_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCron holds the string denoting the cron field in the database.
	FieldCron = "cron"
	// FieldRetention holds the string denoting the retention field in the database.
	FieldRetention = "retention"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the nocodbbackuppolicy in the database.
	Table = "nocodb_backup_policies"
)

// Columns holds all SQL columns for nocodbbackuppolicy fields.
var Columns = []string{
	FieldID,
	FieldConnectionID,
	FieldBaseID,
	FieldUserID,
	FieldEnabled,
	FieldCron,
	FieldRetention,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the NocoDBBackupPolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConnectionID orders the results by the connection_id field.
func ByConnectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionID, opts...).ToFunc()
}

// ByBaseID orders the results by the base_id field.
func ByBaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCron orders the results by the cron field.
func ByCron(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCron, opts...).ToFunc()
}

// ByRetention orders the results by the retention field.
func ByRetention(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetention, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
